import type { DesignCategory } from "../docs/categories";

/**
 * Client-safe metadata for every rendered section design (homepage structure order).
 * Kept free of component imports — some sections read files at render time (fs),
 * so the components themselves live in sectionRegistry.tsx and stay server-side.
 */
export interface SectionMeta {
  /** URL slug — matches the anchor ids used on the /sections list page. */
  slug: string;
  num: string;
  name: string;
  category: DesignCategory;
  tags: string[];
  /** A copy-paste design prompt that would reproduce this section in the HIP design system. */
  prompt: string;
  /**
   * Design family, e.g. "Hero Banner". Members of one family share a single sidebar entry
   * and render as V1/V2… variation tabs on each other's pages; prev/next steps between
   * families, not variants. Omit for standalone sections.
   */
  group?: string;
  /** Short variation-tab label within the family, e.g. "V1". */
  tab?: string;
}

/* Shared prompt preamble so every per-section prompt stands alone. */
const DS =
  "Use the HIP design system: colors only from the global tokens (primary Harbor Teal #3196a9 with its 50–950 ramp, secondary Cyan Pulse, tertiary Periwinkle Dusk, accent Golden Amber, CTA Ember Orange #f97316, navy #0e1f35, base black #030712); fonts Figtree (headers) and Inter (body); responsive section padding 120/60/40, container padding 100/40/20, grid gap 40/30/20; type scale Pre-Header 16/14/12 +3px tracking, H2 56/42/32, Body1 20/18/16.";

export const sectionMeta: SectionMeta[] = [
  {
    slug: "hero",
    num: "01",
    name: "Hero Banner",
    category: "Professional / Corporate",
    tags: ["Full-bleed · Dark overlay · 2-button"],
    group: "Hero Banner",
    tab: "V1",
    prompt: `Design a full-viewport hero banner for an orthodontic practice website. ${DS} Structure: a 44px utility bar (social dots in cta-500, uppercase 11px utility links: Call/Text, Payment Calculator, Referral, Portal, Virtual Consult), a 76px main nav (HIP logo with orange period, uppercase Figtree 700 15px links, cta-500 pill "Free Consult" button), then a left-aligned hero block: cta-500 uppercase eyebrow, Figtree 600 clamp(44–80px) H1 with one word highlighted in cta-500, and two pill buttons (primary cta-500, secondary white with cta text). Background: navy→primary-800/900 gradient with a dark base-black overlay at 70%.`,
  },
  {
    slug: "hero2",
    num: "01B",
    name: "Hero Banner — Pill Nav",
    category: "Modern",
    tags: ["Pill Nav · Full-bleed · Centered text"],
    group: "Hero Banner",
    tab: "V2",
    prompt: `Design an alternative full-bleed hero with a floating pill navigation. ${DS} Topbar in navy; the main nav is a white pill (border-radius 100px 0 0 100px, soft shadow) offset from the left edge. Hero content is centered: Figtree 800 clamp(52–80px) headline over a navy→primary-600/700/800 gradient. Buttons pair a circular icon container with uppercase text; CTA in cta-500, secondary in primary-500.`,
  },
  {
    slug: "hero3",
    num: "01C",
    name: "Hero Banner — Slider",
    category: "Elegant",
    tags: ["Cyan topbar · Inset photo · Serif headline"],
    group: "Hero Banner",
    tab: "V3",
    prompt: `Design a slider-style hero (Figma Master V3 node 12978:55076). ${DS} Structure: a secondary (cyan) utility bar with black ink — social icons left (Facebook, Instagram, YouTube), uppercase overline utility links right (Call/Text, Payment Calculator, Refer a Patient, Español); a white square-cornered main nav (logo, capitalized Menu-Item links with chevrons, square accent "Free Consultation" button — no pill radius). Hero: the photo sits inset inside the 64px page gutter, dark 50% multiply overlay, content bottom-left. Headline in Georgia serif clamp(44–100px), line one white, line two split secondary + accent ("Let Our Family / Treat Your Family"). CTA is the v2 button: cta-700 bar with an uppercase label that slides up on hover, plus a cta-500 icon block holding a diagonal arrow that straightens on hover.`,
  },
  {
    slug: "hero4",
    num: "01D",
    name: "Hero Banner — Centered Nav",
    category: "Professional / Corporate",
    tags: ["Navy topbar · Centered logo · Two-tone headline"],
    group: "Hero Banner",
    tab: "V4",
    prompt: `Design a hero with a centered-logo header over a photo (Figma Master V3 node 15914:55342). ${DS} Structure: a solid navy utility bar with a white-alpha/10 hairline (social icons left — Facebook, Instagram, YouTube — and, right, a phone overline "Call / Text" link plus a compact navy "Request Appointment" button outlined in a 2px white border); a transparent main nav sitting over the photo with the HIP logo centered between two Menu-Item link groups (Our Practice / Services · Patient Resources / Contact Us), each link capitalized with a chevron. Hero content is bottom-left over a navy 70% overlay: a Header-1 two-tone headline whose middle line ("Through Compassionate") takes the pale primary-200 accent while the rest stays white, and a bordered CTA — navy fill, 2px white border, uppercase Button-scale label followed by a short white rule. Fallback ground is a navy→primary-800→primary-600 gradient.`,
  },
  {
    slug: "hero5",
    num: "01E",
    name: "Hero Banner — Boxed Nav",
    category: "Minimalist",
    tags: ["Cream boxed nav · Inset photo · Line Arrow CTAs"],
    group: "Hero Banner",
    tab: "V5",
    prompt: `Design a boxed-nav hero (Figma "hip-Image" Template 06, node 41:22665). ${DS} Nav sits inside the container gutter with secondary-50 hairline borders: a cream (secondary-50) utility bar holding social icons (white hairline dividers), Overline utility links (Call/Text, Payment Calculator, Portal), and two solid nav buttons (cta and primary fills); below, a bordered menu row with the logo left and capitalized Menu-Item links with chevrons right. Hero: photo inset in the gutter under a 50% black overlay, centered uppercase Main Header headline ("We Make / You Smile!"), and two global Line Arrow buttons (cta and primary tones, white labels for the photo ground).`,
  },
  {
    slug: "highlights",
    num: "02",
    name: "Highlights — Trust Badges Grid",
    category: "Clean",
    tags: ["Gray bg · 4-col × 2 rows · Icon + text"],
    group: "Highlights",
    tab: "V1",
    prompt: `Design a trust-badges highlights strip. ${DS} Section on gray-100 with a centered heading using the standard Text Container (eyebrow + H2, no button); 8 cards in a 4-column desktop grid on the DS grid gap (2-col tablet, 1–2 col mobile). Each card: white bg, gray-200 border, icon in a primary-50 rounded square, H6 title (Figtree 700, 20/18/16) in textcolor-h2, Body2 subline (Inter, 18/16/14) in textcolor-body. Badges: Locally Owned, Board-Certified, Locations, Invisalign tier, Flexible Times, Transfers, Interest-Free, Advanced Tech.`,
  },
  {
    slug: "highlights2",
    num: "02B",
    name: "Highlights — Trust Badges (Figma)",
    category: "Clean",
    tags: ["Cream bg · 4-col × 2 rows · Icon + text"],
    group: "Highlights",
    tab: "V2",
    prompt: `Design the Figma "Highlights" trust-badge grid. ${DS} Section ground accent-50 with cards on base-white and a 1px accent-200 border, square corners, no shadow. Titles H6 (Figtree 700, 20/18/16 +0.5px) in textcolor-h2; sublines Body2 (Inter 400, 18/16/14) in textcolor-body; icons primary-500 at 48px (33px mobile). Container ladder 1240/688/280 on the DS section padding and grid gap.`,
  },
  {
    slug: "highlights3",
    num: "02C",
    name: "Highlights — Split Card Stack",
    category: "Fun / Playful",
    tags: ["Accent bg · H2 left · Bordered card stack"],
    group: "Highlights",
    tab: "V3",
    prompt: `Design a split highlights section (Figma "hip-Image", node 53:23534). ${DS} Ground accent-100 tint. Left (max 531px): the standard Text Container with a two-line capitalized H2 "Experience Amazing!". Right (605px): a stack of five white cards, 24px apart, each with a 2px accent-200 border, 20px radius, and 16/24px padding — a primary-500 icon (48px) from the icon library beside an uppercase Subtitle title and gray-800 Body2 copy. Cards: Joy in Practice, Compassionate Care, Growth Mindset, Team Unity, Innovation and Responsibility. The comp's mascot illustration and doodles are decorative assets and are omitted.`,
  },
  {
    slug: "highlights4",
    num: "02D",
    name: "Highlights — Dark Band Grid",
    category: "Bold",
    tags: ["Black bg · Rounded 3×2 grid · Icon + label"],
    group: "Highlights",
    tab: "V4",
    prompt: `Design a highlight band (Figma "hip-Image", node 53:23644). ${DS} Ground base-black with 50/60px padding. A rounded 25px band holds a 3×2 grid of cloud cells (gray-50 fills split by 1px white hairlines): each cell pairs a 64px primary icon from the icon library with a small uppercase Over Line label in the dark heading ink — Free Shuttle Service, Board-Certified Orthodontist, Two Convenient Locations, Same-Day Consultations, 0% Financing & Low Down Payments, All Digital Upgrades (No Impressions). Client-specific credentials are genericized.`,
  },
  {
    slug: "highlights5",
    num: "02E",
    name: "Highlights — Tinted Panel Grid",
    category: "Clean",
    tags: ["Primary-100 panel · 4×2 outlined cards · Centered icons"],
    group: "Highlights",
    tab: "V5",
    prompt: `Design a highlight panel (Figma "hip-Image", node 55:23675). ${DS} White ground, 80px gutters. A primary-100 tinted panel (8px radius, 60px padding, max 1280px) holds a 4×2 grid of outlined cards, 30px apart — each a 1px primary-400 border with 4px radius and 30px padding, stacking a centered 56px primary icon from the icon library over a centered Strong-1 label in the deep primary ink. Items: Family Owned & Community Focused, 2 Convenient Locations, Free Shuttle Service, 0% Financing & Most Insurances Accepted, Charity Cafe Serving Free Coffee, More Than 20,000 Smiles Created, Same-Day Consults & Starts, 50+ Years Serving Our Community. Region-specific copy is genericized.`,
  },
  {
    slug: "steps",
    num: "03",
    name: "Step Section — Simple & Affordable",
    category: "Bold",
    tags: ["Dark bg · 2-col + 3 numbered cards"],
    group: "Step Section",
    tab: "V1",
    prompt: `Design a dark 3-step process section. ${DS} Section on base-black. Left column: the standard Text Container recolored for the dark ground — cta-500 uppercase eyebrow, white H2 (global H2 scale), Body1 copy at 65% white — ending in the global Bold Fill button (accent Golden Amber). Right: 3:2 image placeholder on a navy→cta-500 gradient. Below, three cards on 4% white with oversized Figtree 800 72px step numerals in cta-500 at 18% opacity, H6 white titles, Body2 copy at 55% white.`,
  },
  {
    slug: "steps2",
    num: "03B",
    name: "Step Section — Light Arches",
    category: "Minimalist",
    tags: ["White + primary-100 band · Arch cards · 2 CTAs"],
    group: "Step Section",
    tab: "V2",
    prompt: `Design a light 3-step process section (Figma reference node 12983:54203). ${DS} White ground with a primary-100 band across the lower third, behind the cards. Top row: the standard Text Container left (eyebrow + H2, no button) and, on the right, a copy-only Text Container (Body1 paragraph) ending in two global Minimal Outline buttons retargeted to the cta fill ("Free Ortho Consult") and secondary fill ("Dental Appointment") with base-black labels. Below: three arch-top photo cards (radius-full arch, radius-md base, 4px white frame, middle card taller and raised, side cards bottom-aligned) on the DS grid gap, each followed by a clickable white radius-md label card with a centered two-line Strong 1 label (Inter 700, 20/30 +0.5px) linking to its step's page.`,
  },
  {
    slug: "steps3",
    num: "03C",
    name: "Step Section — Leaf Cards",
    category: "Elegant",
    tags: ["Accent band · 150px corner panel · Leaf cards"],
    group: "Step Section",
    tab: "V3",
    prompt: `Design an elegant 3-step process section (Figma reference node 12985:55117). ${DS} An accent-colored side band with a white content panel over it, rounded 150px at the top-left. Top row: the standard Text Container left (eyebrow + H2, no button) and, right, a copy-only Text Container (Body1 paragraph) ending in the global Elegant Fill button labeled "Complimentary Consult". Below: three leaf cards (150px top-left/bottom-right, radius-md on the other corners, padding and gaps on the DS grid gap) with grounds stepping through tertiary-700 / tertiary-900 / accent-700; each holds a leaf-shaped photo, an outlined serif numeral (transparent fill, 2px white stroke, system serif), and a white Button-scale two-line label. White text must pass contrast on every card ground.`,
  },
  {
    slug: "steps4",
    num: "03D",
    name: "Step Section — Overlap Cards",
    category: "Fun / Playful",
    tags: ["White bg · Photo overlap · 3 colored cards"],
    group: "Step Section",
    tab: "V4",
    prompt: `Design a playful 3-step process section (Figma Master V3 node 12986:56347). ${DS} White ground. Split header aligned to the baseline: left, an eyebrow led by a 50px rule plus a two-line H2 whose first line sits in the cta hue and whose second line is white text on a primary-base box (3×10px padding, 4px radius); right, a copy-only standard Text Container (Body1 paragraph, no button). Below: one large photo rounded 40px (ratio 1240:659), with three rounded-40 step cards overlapping its bottom edge by ~243px on the DS grid gap — grounds tertiary-700 / secondary-700 / primary-700. Each card holds a 138px light (gray-50) numeral tile rounded 20px crossed behind by a 10px gray-50 divider band, the numeral (72/86 bold) repeating the card's hue, and a white uppercase Button-scale two-line label. Centered below, two global Press Shadow buttons: "Free Ortho Consult" and "Dental Appointment". Cards stack 3-across → 3-across tightened → single column down the breakpoints.`,
  },
  {
    slug: "steps5",
    num: "03E",
    name: "Step Section — Serif Outline",
    category: "Elegant",
    tags: ["White bg · Serif heading · Outlined cards"],
    group: "Step Section",
    tab: "V5",
    prompt: `Design an elegant serif 3-step section (Figma Master V3 node 12991:55562). ${DS} White ground. Centered two-line uppercase heading in a system serif on the H2 scale at weight 400 — line one black flanked by 130px gray-300 rules, line two muted gray-500 — over a centered Body1 (Inter 300) intro. Below: three outlined step cards (2px borders cycling accent-500 / tertiary-500 / secondary-400, 30px radius, 32×40 padding), each with a serif numeral on the H3 scale and an uppercase PreHeader-tracked (16/24 +3px) two-line label. Then a wide rounded-30 photo (ratio 1240:563) with a white circular play badge on its top-left corner (rotating practice-name text ring, gray-500 play disc). A split lower row pairs a left-aligned serif heading ("No Pressure" + rule / "Just Answers" muted) with a right Body1 paragraph. One centered global Press Shadow button "Request Free Consult".`,
  },
  {
    slug: "steps6",
    num: "03G",
    name: "Step Section — Ruled List",
    category: "Minimalist",
    tags: ["White bg · Hairline header · Ruled steps"],
    group: "Step Section",
    tab: "V6",
    prompt: `Design an editorial ruled-list step section (Figma "hip-Image" Template 3, node 1:48391). ${DS} White ground. Centered standard Text Container (eyebrow + H2, no button) over a full-width 1px hairline at 20% black. Below, a two-column row: left, a tall square-cornered photo (ratio 547:624); right, a Body1 intro, the global Square Arrow button (cta), and a ruled step list — 3px black rules bounding each row of "STEP 0N:" (Strong 1, colors cycling cta-500 / secondary-500 / tertiary-500) beside a capitalized H4 Alt step title.`,
  },
  {
    slug: "steps7",
    num: "03H",
    name: "Step Section — Number Band",
    category: "Bold",
    tags: ["Bordered row · Color blocks · Outlined numbers"],
    group: "Step Section",
    tab: "V7",
    prompt: `Design a step section with a color-block number band (Figma "hip-Image" Template 06, node 1:48601). ${DS} White ground. A secondary-50 hairline-bordered row (top and right): tall square-cornered photo left (ratio 588:590); right, the standard Text Container (H2 "Upgrading Your Smile Is Easy" + Body1) ending in the global Line Arrow button (cta tone). Below, three flush full-width color blocks (primary-500 / cta-500 / gray-600, 293px tall), each centered with an outlined step number on the Main Header scale (transparent fill, 2px 60%-white stroke) over an uppercase H5 two-line label in white.`,
  },
  {
    slug: "practice",
    num: "04",
    name: "Our Practice — Video",
    category: "Professional / Corporate",
    tags: ["Light teal bg · 2-col · Rotating play badge"],
    group: "Our Practice",
    tab: "V1",
    prompt: `Design a practice-intro video section. ${DS} Section on primary-50, two columns: a 4/3 video placeholder on a primary-900→700 gradient with a rotating circular text ring (SVG textPath, cta-500 at 70%) around a cta-500 play button with a 35% orange glow; and the standard Text Container (eyebrow, H2, Body1 copy) ending in the global Corporate Arrow button (tertiary).`,
  },
  {
    slug: "practice2",
    num: "04B",
    name: "Our Practice — Dark Serif",
    category: "Elegant",
    tags: ["Dark bg · Stat card overlap · Highlights list"],
    group: "Our Practice",
    tab: "V2",
    prompt: `Design a dark elegant practice-intro section (Figma Master V3 node 12994:55984). ${DS} Ground base-black. Split header: left, a two-line uppercase system-serif heading on the H2 scale at weight 400 — line one white trailed by a 130px gray-300 rule, line two in accent-500; right, a white Body1 (Inter 300) paragraph (max 514px). An accent-500 stat card (30px padding and radius, dark ink, serif "24+" at 72/86 over a Strong-1 "Years of Experience" label, 260px wide) overlaps the top-right corner of a wide rounded-30 team photo (ratio 1240:700). Below, a two-column footer row: left, three Strong-1 white highlight rows divided by 2px gray-700 hairlines ending in the global Press Shadow button "Discover the Difference"; right, two rounded-top (20px) portrait photos (536px tall) bottom-aligned. Stack header, photo, list, then gallery down the breakpoints.`,
  },
  {
    slug: "practice3",
    num: "04C",
    name: "Our Practice — Why Us Card",
    category: "Professional / Corporate",
    tags: ["White bg · Card overlap · Credibility strip"],
    group: "Our Practice",
    tab: "V3",
    prompt: `Design a practice-intro section with an overlapping highlight card (Figma Master V3 node 12998:56855). ${DS} White ground. Header row: left, a smile glyph, a tracked uppercase eyebrow in tertiary-900, and a semibold capitalized two-line H2; right, a tertiary-700 card with asymmetric corners (50px top-left/bottom-right, 5px the others), a 2px white border, 60px padding — holding a white semibold H3 "Why Us?", a Body1 paragraph, and three extrabold Strong-1 bullet rows led by the braces glyph, divided by 10%-white hairlines. The card overlaps the top of a full-bleed edge-to-edge photo (ratio 1920:717, no radius). Below: an uppercase semibold H5 statement (max 627px) beside a tertiary-900 "Learn More" button with mirrored 40px top-left/bottom-right corners and an arrow. Finish with a credibility strip between 1px gray-200 hairlines — grayscale wordmarks (AAO, Board-Certified, ADA, iTero, Opalescence) spaced across the container.`,
  },
  {
    slug: "practice4",
    num: "04D",
    name: "Our Practice — Accent Card",
    category: "Fun / Playful",
    tags: ["Light teal bg · Rounded photos · Accent card"],
    group: "Our Practice",
    tab: "V4",
    prompt: `Design a light playful practice-intro section (Figma "hip-Image" Template 11, node 1:49780). ${DS} Ground primary-50. Centered standard Text Container (H2 + Body1 intro, no eyebrow, no button). Below: one wide rounded-30 photo (ratio 1240:660). Then a two-column row: left, an accent-500 rounded-30 card (60px padding) holding two capitalized Subtitle Alt (bold 24/36 +0.75px) paragraphs in dark ink; right, a 532px column with a rounded-30 photo (ratio 532:520) and, bottom-right beneath it, the global Press Shadow button "Discover the Difference". Cards and photos stack full-width down the breakpoints.`,
  },
  {
    slug: "practice5",
    num: "04F",
    name: "Our Practice — Editorial Split",
    category: "Minimalist",
    tags: ["Light bg · Offset copy · Logo band"],
    group: "Our Practice",
    tab: "V5",
    prompt: `Design an editorial practice-intro section with a credibility band (Figma "hip-Image" Template 3, node 36:22665). ${DS} Main block on primary-50: left, the standard Text Container (eyebrow + two-line H2) with a second copy-only Text Container indented to the right below it (Body1 + the global Square Arrow button, secondary tone); right, a tall square-cornered photo (ratio 639:664). Close with a primary-500 logo band — white credibility marks from the shared logo library (AAO, ABO, ADA, iTero, Invisalign, 3M Clarity) at icon-3xl height, centered with generous gaps.`,
  },
  {
    slug: "practice6",
    num: "04H",
    name: "Our Practice — Pull-Quote",
    category: "Minimalist",
    tags: ["Cream bg · White band · Quote bar + arrow list"],
    group: "Our Practice",
    tab: "V6",
    prompt: `Design a cream practice-intro section (Figma "hip-Image" Template 06, node 1:48610). ${DS} Ground secondary-50 with a white band across the lower 55% behind the content. Left: a tall square-cornered photo (ratio 625:528). Right: the standard Text Container (H2 "What Sets Us Apart" + Body1), then a white pull-quote bar with a 4px cta-500 left rule (Body1), an arrow-bullet Strong-1 highlight list (cta arrows), and the global Line Arrow button (primary tone) "Discover Us".`,
  },
  {
    slug: "doctors",
    num: "05",
    name: "Our Doctors",
    category: "Clean",
    tags: ["White bg · Centered heading · Zig-zag rows"],
    group: "Our Doctors",
    tab: "V1",
    prompt: `Design a meet-the-doctors section. ${DS} White section, centered heading block using the standard Text Container (eyebrow, H2, Body1 intro, no button). Zig-zag rows on the DS grid gap alternate photo and bio: photo placeholders on primary gradients, credential pill (primary-50 bg / primary-200 border / cta text), H3 name (Figtree 800, 42/36/28) in textcolor-h3, Body2 bio (Inter, 18/16/14) in textcolor-body, and the global Clean Outline button labeled "Meet Dr. <last name>". Keep bios to two sentences.`,
  },
  {
    slug: "doctors2",
    num: "05B",
    name: "Our Doctors — Highlight List",
    category: "Minimalist",
    tags: ["Gray bg · Check list · Edge-bleed photo"],
    group: "Our Doctors",
    tab: "V2",
    prompt: `Design a meet-the-doctor section (Figma "hip-Image" Template 3, node 1:48413). ${DS} Ground gray-50 with a deep left indent. Left column: the standard Text Container (eyebrow, H2 "Meet the Doctor", Body1) over three highlight items — each a secondary-500 check icon beside a Strong 1 title with a Body1 line under it — ending in the global Square Arrow button (secondary tone) "Meet the Doctor". Right: a tall square-cornered portrait photo bleeding to the section's right edge (ratio 525:572).`,
  },
  {
    slug: "doctors3",
    num: "05C",
    name: "Our Doctors — Bordered Card",
    category: "Minimalist",
    tags: ["Logo row · Cream-bordered card · Filled Line Arrow"],
    group: "Our Doctors",
    tab: "V3",
    prompt: `Design a meet-the-team section (Figma "hip-Image" Template 06, node 1:48621). ${DS} White ground. Top: a dimmed (60%) credibility logo row from the shared logo library (AAO, ABO, ADA, iTero, Invisalign — black variants at icon-3xl, spread edge to edge). Below: a secondary-50-bordered card on 70% white with a deep left inset — the standard Text Container (eyebrow, H2 doctor name, two Body1 paragraphs) ending in the global Line Arrow button (primary tone, filled white) "Meet the Doctor", beside a tall portrait photo (ratio 615:688) flush with the card's right edge.`,
  },
  {
    slug: "doctors4",
    num: "05D",
    name: "Our Doctors — Gray Cards",
    category: "Clean",
    tags: ["White bg · Gray duo cards · Square Arrow CTA"],
    group: "Our Doctors",
    tab: "V4",
    prompt: `Design a two-doctor section (Figma "hip-Image", node 53:23342). ${DS} White ground. Centered standard Text Container heading (H2 "Meet Your Smile Experts" + Body1, max 870px). Two full-width gray-100 cards, 30px apart and 40px padded, alternating copy/portrait with a 60px gap: each copy column opens with a thin accent rule carrying a leading dot, then a capitalized H3 doctor name, Strong-1 credentials in gray-600, a Body1 bio, and the global Square Arrow button (secondary tone — black border, dark ink) "Meet Dr. …". Portraits are tall (549:605) and flush with the card padding. First card copy-left, second mirrored.`,
  },
  {
    slug: "doctors5",
    num: "05E",
    name: "Our Doctors — Portrait Columns",
    category: "Elegant",
    tags: ["Gray-50 bg · Team banner · Modern Pill CTA"],
    group: "Our Doctors",
    tab: "V5",
    prompt: `Design a two-doctor section with a team banner (Figma "hip-Image", node 53:23475). ${DS} Ground gray-50. Top: a wide team photo (1280:534) inset 80px from each page edge. Centered standard Text Container heading (H2 "Specialists Focusing On Orthodontics" + Body1 in gray-600, max 870px). Two equal columns, 80px apart: each a tall portrait (580:600), then a 60px 2px cta-500 divider, a capitalized H3 doctor name in the primary hue with a smaller inline credential (DMD), gray-600 Body1 bio, and the global Modern Pill button retargeted to the gray ramp (gray-600 fill, gray-800 hover) "Meet Dr. …".`,
  },
  {
    slug: "who-we-help",
    num: "06",
    name: "Who We Help — Kids / Teens / Adults",
    category: "Fun / Playful",
    tags: ["Light teal bg · Centered heading · Zig-zag rows"],
    group: "Who We Help",
    tab: "V1",
    prompt: `Design an audience-segments section for Kids, Teens and Adults. ${DS} Section on primary-50 with a centered heading block using the standard Text Container (eyebrow, H2, Body1 intro, no button). Three zig-zag rows on the DS grid gap, each with a 3:2 image placeholder (white→primary-300 / white→cta-300 / white→tertiary-300 gradients), an age pill (white bg, primary-200 border, cta text), H3 title (Figtree 800, 42/36/28) in textcolor-h3, Body2 copy (Inter, 18/16/14) in textcolor-body, and the global Press Shadow button (Fun / Playful) linking to that audience's landing page. Rows divided by primary-100 borders.`,
  },
  {
    slug: "who-we-help2",
    num: "06B",
    name: "Who We Help — Column Cards",
    category: "Minimalist",
    tags: ["White bg · Hairline columns · Text links"],
    group: "Who We Help",
    tab: "V2",
    prompt: `Design an editorial audiences section (Figma "hip-Image" Template 3, node 1:48460). ${DS} White ground. Split header: the standard Text Container (eyebrow + two-line H2) left, a copy-only Body1 Text Container right, over a full-width gray-200 hairline. Below, three hairline-divided columns for Kids / Teens / Adults — each an H3 title, Body1 copy, two uppercase Button-scale text links with arrow icons ("Braces" in secondary-500, "Clear Aligners" in cta-500), and a tall photo filling the rest of the 662px column; the middle column runs image-first.`,
  },
  {
    slug: "who-we-help3",
    num: "06C",
    name: "Who We Help — Mosaic Cards",
    category: "Bold",
    tags: ["Cream bg · Photo mosaic · Colored cards"],
    group: "Who We Help",
    tab: "V3",
    prompt: `Design an audiences section with a photo mosaic (Figma "hip-Image" Template 06, node 1:48633). ${DS} Ground secondary-50, no left gutter: a full-height photo mosaic bleeding to the left edge (two portraits over one wide image, spacing-4 gaps). Right column (532px, padded 100px vertical): the standard Text Container (two-line H2 "Orthodontics for everyone"), then three colored audience cards (primary-500 / cta-500 / gray-600, 40px padding) — each an H3 title beside Body1 copy and two uppercase white Button-scale text links with arrows (Braces / Invisalign) spread apart.`,
  },
  {
    slug: "who-we-help4",
    num: "06D",
    name: "Who We Help — Photo Columns",
    category: "Fun / Playful",
    tags: ["Primary-100 bg · Rounded photo · Hue-coded links"],
    group: "Who We Help",
    tab: "V4",
    prompt: `Design a stacked audiences section (Figma "hip-Image", node 53:23158). ${DS} Ground primary-100 tint. Centered standard Text Container (cta uppercase preheader "Orthodontics For Everyone", H2 "Who We Help", Body1, max 768px). Below, a full-width family photo with 24px rounded corners (ratio 1240:585). Then three equal audience columns — Kids, Teens, Adults — each a capitalized H3 in base-black, Body1 copy, and a pair of uppercase Button-scale text links with up-right arrows: Braces in primary-500 and Invisalign in cta-500, 30px apart.`,
  },
  {
    slug: "who-we-help5",
    num: "06E",
    name: "Who We Help — Slate Cards",
    category: "Elegant",
    tags: ["Secondary-600 bg · Left-bleed photo · Hairline cards"],
    group: "Who We Help",
    tab: "V5",
    prompt: `Design a slate audiences section (Figma "hip-Image", node 53:23211). ${DS} Ground secondary-600. Split heading: the standard Text Container in white (uppercase preheader "Orthodontics For Everyone", H2 "Who We Help") left, a white Body1 intro (max 543px) right. A full-width photo (1340:720) bleeds to the left page edge keeping the right gutter. Below, inset ~220px from the left and flush with the right gutter, three white cards (50px padding) divided by 1px gray-100 hairlines — each a capitalized H3 in the primary hue, gray-800 Body1, and two stacked uppercase Button-scale text links with right arrows: InBrace (secondary-600) and Braces (cta-600), 20px apart.`,
  },
  {
    slug: "how-we-help",
    num: "07",
    name: "How We Help — Treatments",
    category: "Clean",
    tags: ["White bg · Centered heading · Zig-zag rows"],
    group: "How We Help",
    tab: "V1",
    prompt: `Design a treatments overview section. ${DS} White section, centered heading block using the standard Text Container (eyebrow, H2, Body1 intro, no button). Zig-zag rows per treatment on the DS grid gap: 3:2 image placeholder on primary/cta/tertiary tint gradients, treatment tag pill (primary-50 bg, primary-200 border, cta text), H3 title (Figtree 800, 42/36/28) in textcolor-h3, Body2 copy (Inter, 18/16/14) in textcolor-body, and the global Clean Outline button labeled "Explore <treatment>". One image per treatment, matched to the treatment.`,
  },
  {
    slug: "how-we-help2",
    num: "07B",
    name: "How We Help — Full-Bleed Rows",
    category: "Minimalist",
    tags: ["Full-bleed halves · Alternating · Square CTA"],
    group: "How We Help",
    tab: "V2",
    prompt: `Design a full-bleed treatments section (Figma "hip-Image" Template 3, node 1:48493). ${DS} White ground. Centered standard Text Container (eyebrow, H2, Body1). Then three edge-to-edge alternating rows with no gaps, each 550px: half photo, half white panel whose inner block (max 460px) holds a capitalized H3 in primary-500, Body1 copy, and the global Square Arrow button (primary tone) labeled "Explore <treatment>". Rows cover Braces, Clear Aligners, Early Treatment.`,
  },
  {
    slug: "how-we-help3",
    num: "07C",
    name: "How We Help — Bordered Rows",
    category: "Minimalist",
    tags: ["Gray bg · Bordered rows · Hue-coded titles"],
    group: "How We Help",
    tab: "V3",
    prompt: `Design a two-treatment section (Figma "hip-Image" Template 06, node 1:48645). ${DS} Ground gray-50. Split heading: the standard Text Container (two-line H2 "How / We Help") left, a Body1 paragraph (max 577px) right. Two hairline-bordered rows with 100px gaps, alternating text/photo: Invisalign first (tertiary-100 border, H2 title in cta-500, Body1, global Line Arrow button cta tone), then Braces (secondary-50 border, photo left, H2 title in primary-500, Line Arrow primary tone). Photos are tall and flush with the row edge (ratio 585:550).`,
  },
  {
    slug: "how-we-help4",
    num: "07D",
    name: "How We Help — Card Slabs",
    category: "Vibrant",
    tags: ["Gray bg · White cards · Edge color slabs"],
    group: "How We Help",
    tab: "V4",
    prompt: `Design a three-treatment section (Figma "hip-Image", node 51:23018). ${DS} Ground gray-50. Centered standard Text Container heading (cta preheader "Our Treatments", primary H2 "How We Help", Body1, max 826px). Three alternating full-width rows, 100px apart: each pairs a white card (rounded 24px outer corners, 120px inner padding, holding a Text Container with an H3 in the row's hue, Body1, and the global Pill Arrow button — rounded 8px, up-right arrow — in the same hue) with a tall photo (515:600) and a 120px color slab bleeding to the page edge. Rows: Braces (primary), Invisalign (cta, mirrored), Other Treatments (base-black slab, gray-800 dark button).`,
  },
  {
    slug: "how-we-help5",
    num: "07E",
    name: "How We Help — Hairline Rows",
    category: "Elegant",
    tags: ["White bg · Edge-bleed photos · Secondary pill CTA"],
    group: "How We Help",
    tab: "V5",
    prompt: `Design a four-treatment section (Figma "hip-Image", node 52:23078). ${DS} White ground. Centered standard Text Container heading (preheader "Treatment For Everyone", H2 "How We Help", Body1, max 833px). Four alternating rows, 80px apart, each pairing a tall photo (692:600) bled flush to one page edge with a Text Container (capitalized H2 title, Body1, global Pill Arrow button in the secondary tone) in the opposite gutter; a 1px 15%-black hairline runs from the title line out to the page edge. Rows: InBrace, Clear Aligners (mirrored), Braces, Other Treatments (mirrored).`,
  },
  {
    slug: "instagram",
    num: "08",
    name: "Instagram Section",
    category: "Vibrant",
    tags: ["White bg · Horizontal scroll · Square tiles"],
    prompt: `Design an Instagram feed strip. ${DS} Section on accent-50 with the standard Text Container: "We're Social" eyebrow, "Connect With Us" H2, and the @username in H4 Alt (Figtree 700, 32/28/24, lowercase) in textcolor-body. Below: 310×414 post tiles (gray-100 on gray-200 borders) in a scroll-snap slider on the 30/20/16 gap ladder. Footer row: Subtitle "FOLLOW US" with Facebook/Instagram/X/TikTok icons in primary separated by gray-200 lines, and square slider arrows with a 2px primary border (fill primary on hover). Deliberately no orange CTA so it never competes with the main conversion CTA.`,
  },
  {
    slug: "cta",
    num: "09",
    name: "CTA Section — Get Started",
    category: "Vibrant",
    tags: ["Orange-tinted bg · Image left · 1 CTA only"],
    group: "CTA Section",
    tab: "V1",
    prompt: `Design a conversion CTA section. ${DS} Section on a cta-50→cta-100 gradient, two columns: 3:2 image placeholder left (cta-200→400 gradient), and the standard Text Container right (eyebrow, H2, Body1 copy) ending in the global Vibrant Sweep button retargeted to the CTA ramp — the page's one conversion CTA stays Ember Orange with a 35% orange shadow. Exactly one CTA — no competing links.`,
  },
  {
    slug: "cta2",
    num: "09B",
    name: "CTA Section — Orange Panel",
    category: "Bold",
    tags: ["cta panel · Offset photo · 1 CTA only"],
    group: "CTA Section",
    tab: "V2",
    prompt: `Design a bold conversion CTA (Figma "hip-Image" Template 3, node 1:48525). ${DS} A cta-500 panel spans ~76% of the width with generous padding, holding a white uppercase eyebrow (PreHeader), a white capitalized two-line H2 ("Are you ready to transform your smile?"), and the global Square Arrow button (cta fill, white border). A square-cornered portrait photo (ratio 635:632) overlaps the panel's right edge, vertically centered and offset past the section's top and bottom. Exactly one CTA.`,
  },
  {
    slug: "cta3",
    num: "09C",
    name: "CTA Section — Teal Band",
    category: "Vibrant",
    tags: ["cta overlay · Centered · 1 CTA only"],
    group: "CTA Section",
    tab: "V3",
    prompt: `Design a full-bleed conversion band (Figma "hip-Image" Template 06, node 1:48663). ${DS} A 554px band: full-bleed photo under a cta-500 overlay at 96%; centered standard Text Container recolored white (capitalized H2 "Get Started Today!" + Body1, max 659px) ending in the global Line Arrow button (white tone) "Request Free Consult". Exactly one CTA. The comp's corner doodles are decorative assets and are omitted.`,
  },
  {
    slug: "cta4",
    num: "09D",
    name: "CTA Section — Capsule Photo",
    category: "Fun / Playful",
    tags: ["cta-500 band · Pill photo ring · Clean Expand CTA"],
    group: "CTA Section",
    tab: "V4",
    prompt: `Design a conversion band with a capsule photo (Figma "hip-Image", node 49:22981). ${DS} Full-bleed cta-500 band, 80px column gap. Left: the standard Text Container recolored white (uppercase preheader "Request A Free Consult", capitalized H2 "Get Started Today Right Away") ending in the global Clean Expand button, retargeted to the cta ramp for ground contrast (white pill, cta-500 icon badge and label, fills solid cta-500 on hover) "Request Free Consult"; exactly one CTA. Right (46%): a pill-shaped photo fully rounded inside a 5px white ring with a 24px inset. Concentric cta-600 contour rings sweep the bottom-right corner (CSS repeating-radial-gradient, standing in for the comp's decorative vector).`,
  },
  {
    slug: "cta5",
    num: "09E",
    name: "CTA Section — Inset Band",
    category: "Bold",
    tags: ["White gutters · cta-500 band · Full-height photo"],
    group: "CTA Section",
    tab: "V5",
    prompt: `Design an inset conversion band (Figma "hip-Image", node 49:22998). ${DS} White page gutters (container padding) around a full-bleed cta-500 band, 636px tall, 80px column gap. Left (40%): a doctor photo flush with the band's top, bottom, and left edges. Right: the standard Text Container recolored for the ground — base-black uppercase preheader "Request Free Consult", white capitalized H2 "Get Started On Treatments", white Body1 — ending in the global Pill Arrow button (white tone, rounded 8px corners, diagonal up-right arrow) "Request Free Consult". Exactly one CTA.`,
  },
  {
    slug: "reviews",
    num: "10",
    name: "5-Star Care — Reviews",
    category: "Bold",
    tags: ["Dark bg · 2-col top · Card slider bottom"],
    group: "Reviews",
    tab: "V1",
    prompt: `Design a testimonials section. ${DS} Section on base-black. Top: the standard Text Container recolored for the dark ground (cta-500 eyebrow, white H2, Body1 at 60% white) beside a 3:2 image placeholder on a navy→cta-500 gradient. Bottom: review cards on 5% white with 10% white borders on the DS grid gap — Google G, cta-500 stars, Body2 italic review text at 75% white, uppercase reviewer name at 45% white; slider arrows with 20% white borders and the global Bold Fill button labeled "More Reviews".`,
  },
  {
    slug: "reviews2",
    num: "10B",
    name: "Reviews — Quote Column",
    category: "Minimalist",
    tags: ["White bg · Quote hairline · Framed card"],
    group: "Reviews",
    tab: "V2",
    prompt: `Design an editorial testimonials section (Figma "hip-Image" Template 3, node 1:48508). ${DS} White ground. Left: a tall square-cornered portrait photo (ratio 545:722). Center: a vertical hairline column at 20% black broken by the quote glyph in primary-300. Right: the standard Text Container (eyebrow + H2 "Our 5-star experience"), one framed review card (primary-50 ground, 1px primary-200 border, 60px padding: Google color mark + five accent-500 stars, a Body1 quote, "Read More" in tertiary-500 Strong 1, a 2px gray divider, uppercase Subtitle reviewer name), then a footer row pairing square primary slider arrows with the global Square Arrow button (primary tone) "Read More".`,
  },
  {
    slug: "reviews3",
    num: "10C",
    name: "Reviews — Card Rail",
    category: "Minimalist",
    tags: ["Cream block · Overflow card rail · Square arrows"],
    group: "Reviews",
    tab: "V3",
    prompt: `Design a reviews section with an overflowing card rail (Figma "hip-Image" Template 06, node 1:48669). ${DS} White ground with a secondary-50 block behind the top-left (50% wide, 455px). Left-aligned standard Text Container (H2 "Our Patients Love Us" + Body1). A horizontal rail of gray-50 review cards (370px wide, 50px padding, 30px gap) overflowing the right edge — each with the Google color mark + five accent-500 stars, a Body1 quote, "Read More" in cta-500 Strong 1, a 2px gray divider, and an uppercase Subtitle reviewer name. Footer row: square secondary-50 slider arrow buttons left, the global Line Arrow button (cta tone) "Read More Reviews" right.`,
  },
  {
    slug: "locations",
    num: "11",
    name: "Location Section",
    category: "Professional / Corporate",
    tags: ["White bg · 2-col intro · List + map"],
    group: "Location Section",
    tab: "V1",
    prompt: `Design a locations section. ${DS} White section. Intro row: 3:2 image placeholder (navy→cta-500 gradient) beside the standard Text Container (eyebrow, H2, Body1). Below: location panels on the DS gap tokens (gray-50 bg, gray-200 border, Subtitle headings (Figtree 700, 24/22/18 +0.75px), Body2 addresses, H6 cta-500 phone links — clickable in production) ending in the global Corporate Arrow button "View All Locations", next to a stylized map (primary-50→100 gradient, primary-200 border) with cta-500 teardrop pins.`,
  },
  {
    slug: "locations2",
    num: "11B",
    name: "Location Section — Map Block",
    category: "Professional / Corporate",
    tags: ["Light bg · Map + pins · Info panel on navy"],
    group: "Location Section",
    tab: "V2",
    prompt: `Design a locations section with a bordered map block (Figma "hip-Image" Template 3, node 1:48533). ${DS} Intro on primary-50: the standard Text Container (secondary eyebrow, H2 "Come Visit Us", Body1). Below, a gray-200 hairline-bordered block: a 522px stylized map (light grid ground, teardrop map pins in primary and secondary, a primary-500 location tooltip), then a bottom row — photo left, white info panel right (60px padding) holding a "Locations" column (secondary-600 uppercase Subtitle, four Strong-1 names each with an accent pin + Body1 address), a vertical hairline, and "Contact Us" / "Contact Hours" columns (phone link, six-day hours table). The section's lower band sits on navy, per the comp.`,
  },
  {
    slug: "locations3",
    num: "11C",
    name: "Location Section — Split Map",
    category: "Minimalist",
    tags: ["White bg · Info columns · Map over photo"],
    group: "Location Section",
    tab: "V3",
    prompt: `Design a split locations section (Figma "hip-Image" Template 06, node 1:48682). ${DS} White ground. Left column: the standard Text Container (H2 "Come Visit Us" + Body1), then two info columns — Locations (cta-600 uppercase Subtitle, Strong-1 names with primary map pins + Body1 addresses) and Call/Text, beside an Office Hours column (six-day Body1 table). Right column (42%): a stylized light-grid map (428px, cta teardrop pin) stacked over a square-cornered office photo filling the rest.`,
  },
  {
    slug: "locations4",
    num: "11D",
    name: "Location Section — Pill Capsules",
    category: "Fun / Playful",
    tags: ["Gray-50 bg · Pill photo + map capsules · Popup pin"],
    group: "Location Section",
    tab: "V4",
    prompt: `Design a capsule locations section (Figma "hip-Image", node 46:22841). ${DS} Ground gray-50. Top row: a pill-shaped photo capsule — office photo fully rounded inside a white 16px inset ring and 4px gray-200 border — beside the standard Text Container (preheader "Come Visit Us", H2 "Our Location", Body1). Bottom row: an info column with primary-600 uppercase Subtitle titles — Locations (cta map-pin + Body1 address), Contact Us (cta phone icon + Body1 number), Contact Hours (six-day Body1 table) — beside a large pill-shaped map capsule (white 30px ring, 4px gray-200 border) holding a stylized light-grid map with a popup pin: primary-500 rounded bubble "Location Name" (Strong-1 white, soft shadow) with a triangle tail over a primary map-pin glyph.`,
  },
  {
    slug: "locations5",
    num: "11E",
    name: "Location Section — Map Panel",
    category: "Clean",
    tags: ["Gray-50 bg · Full-width map · Cream info panel"],
    group: "Location Section",
    tab: "V5",
    prompt: `Design a map-panel locations section (Figma "hip-Image", node 48:22851). ${DS} Ground gray-50. Top row: the standard Text Container (preheader "Our Locations", H2 "Come Visit Us", Body1) beside a square-cornered office photo (46%). Bottom row: a full-width stylized light-grid map with rounded left corners, four secondary-hued teardrop pins spread across it, and a white bordered +/− zoom control top right; flush against the map's right edge, a primary-100 info panel (40px padding) with primary-600 uppercase Subtitle titles — Locations (four Strong-1 secondary names, each with a secondary map-pin + Body1 address), Contact Us (phone icon + Body1 number), Contact Hours (six-day Body1 table).`,
  },
  {
    slug: "footer",
    num: "12",
    name: "Footer Section",
    category: "Professional / Corporate",
    tags: ["Navy bg · Logo + CTA · 3 columns · Bottom bar"],
    group: "Footer",
    tab: "V1",
    prompt: `Design a site footer. ${DS} Ground navy. Top row: HIP logo (white, orange period) and the global Corporate Arrow button retargeted to the CTA ramp — the last-chance conversion stays Ember Orange. Three link columns on the DS grid gap with primary-400 uppercase 10px labels and 13px links at 60% white (white on hover). Bottom bar: 11px legal text at 45% white with the required HIPAA links (Privacy Policy, Accessibility Statement, Notice of Privacy Practices). Include the fixed accessibility widget and chat bubble.`,
  },
  {
    slug: "footer2",
    num: "12B",
    name: "Footer — Hairline Columns",
    category: "Minimalist",
    tags: ["Navy bg · Square CTA · Hairline columns"],
    group: "Footer",
    tab: "V2",
    prompt: `Design an editorial site footer (Figma "hip-Image" Template 3, node 1:48549). ${DS} Ground navy. Top row: white brand mark and the global Square Arrow button (cta fill, white border) "Request Free Consult", over a 15%-white hairline. Three hairline-divided columns: Quick Links (primary-300 uppercase Subtitle label + Body1 white links), Contact Us (map-pin and phone icons beside Body1 links), Follow Us (five social icons — Facebook, Instagram, X, YouTube, TikTok — separated by 2px 15%-white dividers). A second hairline, then centered legal text in gray-400 with primary-300 links: copyright, Sitemap | Privacy Policy | Accessibility Statement | Notice of Privacy Practices, and the HIP credit.`,
  },
  {
    slug: "footer3",
    num: "12C",
    name: "Footer — Boxed Columns",
    category: "Bold",
    tags: ["Black bg · Boxed panels · Line Arrow CTA"],
    group: "Footer",
    tab: "V3",
    prompt: `Design a boxed-column site footer (Figma "hip-Image" Template 06, node 1:48698). ${DS} Ground base-black. Top row: white brand mark and the global Line Arrow button (cta tone) "Request Free Consult". Three boxed columns — 5%-white panels with 1px 10%-white borders and 40px padding — for Quick Links (secondary-100 uppercase Subtitle label + Body1 white links), Contact Us (map-pin/phone icons beside Body1 links), and Follow Us (five social icons separated by 2px 15%-white dividers). A 15%-white hairline, then centered Body2 legal text with primary-300 links: copyright, Sitemap | Privacy Policy | Accessibility Statement | Notice of Privacy Practices, and the HIP credit.`,
  },
  {
    slug: "footer4",
    num: "12D",
    name: "Footer — Rounded Card",
    category: "Fun / Playful",
    tags: ["Black bg · White rounded card · Press Shadow CTA"],
    group: "Footer",
    tab: "V4",
    prompt: `Design a card-style site footer (Figma "hip-Image", node 43:22666). ${DS} Ground base-black. A white card with 60px bottom-only rounded corners and 60px padding holds four hairline-divided columns (1px primary-100 right rules): Quick Links (black uppercase Subtitle label + Body1 links), Contact Us (primary map-pin/phone icons beside Body1 links), Follow Us (four primary social icons separated by 2px primary-100 dividers), and the brand column — logo over the global Press Shadow pill (cta tone: cta-500 fill, cta-100 hard shadow) "Request Free Consult". Below on the black ground: centered Body2 legal text in white with accent-300 links (copyright, Sitemap | Privacy Policy | Accessibility Statement | Notice of Privacy Practices, HIP credit), then the joined privacy chip pair — 15%-white 1px borders, 5px outer radius — "Notice at collection" and "Your privacy choices" with the tiny white-check / primary-close toggle.`,
  },
  {
    slug: "footer5",
    num: "12E",
    name: "Footer — Dark Card on Tint",
    category: "Modern",
    tags: ["Cta tint ground · Dark rounded card · Corporate Chevron CTA"],
    group: "Footer",
    tab: "V5",
    prompt: `Design an inset-card site footer (Figma "hip-Image", node 44:22746). ${DS} Page ground cta-200; inside it a base-black card with 20px rounded corners and 100px padding. Brand row: white logo left, the global Corporate Chevron button retargeted to the cta ramp (conversion CTAs always ride the cta color) "Request Free Consult" right, over a 1px 10%-white hairline. Three hairline-divided columns (10%-white right rules, 60px vertical padding): Quick Links (cta-300 uppercase Subtitle label + Body1 white links), Contact Us (cta-300 map-pin/phone icons beside Body1 links), Follow Us (five white social icons separated by 2px 15%-white dividers). A second 10%-white hairline, then centered Body2 white legal text with primary-400 links (copyright, Sitemap | Privacy Policy | Accessibility Statement | Notice of Privacy Practices, HIP credit) and the joined privacy chip pair — 15%-white 1px borders, 5px outer radius — with the tiny white-check / primary-close toggle.`,
  },
];

export function metaBySlug(slug: string): SectionMeta | undefined {
  return sectionMeta.find((entry) => entry.slug === slug);
}
