/**
 * Recognition & Affiliation logo library data — 186 logos exported from the
 * Figma "Recognition - Affiliations Logos" file (node 6883:64229). Each logo ships as
 * SVG files in public/logos (default / black / white variants); `files` holds the
 * public paths the gallery renders and copies.
 * Generated by scratchpad/gen-logo-data.js — regenerate rather than hand-editing.
 */

export type LogoCategory = "associations" | "awards" | "products" | "education" | "insurance" | "community";
export type LogoVariant = "default" | "black" | "white";

export interface LogoEntry {
  name: string;
  slug: string;
  /** Figma frame node id in the logo source file. */
  node: string;
  category: LogoCategory;
  files: Partial<Record<LogoVariant, string>> & { default: string };
}

export const LOGO_CAT_LABELS: Record<LogoCategory, string> = {
  "associations": "Associations & Boards",
  "awards": "Awards & Recognition",
  "products": "Products & Technology",
  "education": "Education",
  "insurance": "Insurance",
  "community": "Community & Media"
};

export const LOGO_CAT_ORDER: LogoCategory[] = ["associations","awards","products","education","insurance","community"];

export const logos: LogoEntry[] = [
  {
    "name": "AAO",
    "slug": "aao",
    "node": "8834:7",
    "category": "associations",
    "files": {
      "default": "/logos/aao--default.svg",
      "black": "/logos/aao--black.svg",
      "white": "/logos/aao--white.svg"
    }
  },
  {
    "name": "aaoms",
    "slug": "aaoms",
    "node": "8892:593",
    "category": "associations",
    "files": {
      "default": "/logos/aaoms--default.svg",
      "black": "/logos/aaoms--black.svg",
      "white": "/logos/aaoms--white.svg"
    }
  },
  {
    "name": "ABO",
    "slug": "abo",
    "node": "8834:15",
    "category": "associations",
    "files": {
      "default": "/logos/abo--default.svg",
      "black": "/logos/abo--black.svg",
      "white": "/logos/abo--white.svg"
    }
  },
  {
    "name": "ABPB - American Board of Pediatric Dentistry",
    "slug": "abpb-american-board-of-pediatric-dentistry",
    "node": "8834:63",
    "category": "associations",
    "files": {
      "default": "/logos/abpb-american-board-of-pediatric-dentistry--default.svg",
      "white": "/logos/abpb-american-board-of-pediatric-dentistry--white.svg",
      "black": "/logos/abpb-american-board-of-pediatric-dentistry--black.svg"
    }
  },
  {
    "name": "Academy of general dentistry",
    "slug": "academy-of-general-dentistry",
    "node": "8871:10924",
    "category": "associations",
    "files": {
      "default": "/logos/academy-of-general-dentistry--default.svg",
      "black": "/logos/academy-of-general-dentistry--black.svg",
      "white": "/logos/academy-of-general-dentistry--white.svg"
    }
  },
  {
    "name": "ADA",
    "slug": "ada",
    "node": "8834:8",
    "category": "associations",
    "files": {
      "default": "/logos/ada--default.svg",
      "black": "/logos/ada--black.svg",
      "white": "/logos/ada--white.svg"
    }
  },
  {
    "name": "ADA",
    "slug": "ada-2",
    "node": "8842:19",
    "category": "associations",
    "files": {
      "default": "/logos/ada-2--default.svg",
      "black": "/logos/ada-2--black.svg",
      "white": "/logos/ada-2--white.svg"
    }
  },
  {
    "name": "ADPAC",
    "slug": "adpac",
    "node": "8845:6733",
    "category": "associations",
    "files": {
      "default": "/logos/adpac--default.svg",
      "black": "/logos/adpac--black.svg",
      "white": "/logos/adpac--white.svg"
    }
  },
  {
    "name": "Adso",
    "slug": "adso",
    "node": "8964:9",
    "category": "associations",
    "files": {
      "default": "/logos/adso--default.svg",
      "black": "/logos/adso--black.svg",
      "white": "/logos/adso--white.svg"
    }
  },
  {
    "name": "alabama academy of pediatric dentistry",
    "slug": "alabama-academy-of-pediatric-dentistry",
    "node": "8851:6113",
    "category": "associations",
    "files": {
      "default": "/logos/alabama-academy-of-pediatric-dentistry--default.svg",
      "black": "/logos/alabama-academy-of-pediatric-dentistry--black.svg",
      "white": "/logos/alabama-academy-of-pediatric-dentistry--white.svg"
    }
  },
  {
    "name": "american academy of facial esthetics Aafe.",
    "slug": "american-academy-of-facial-esthetics-aafe",
    "node": "8866:8411",
    "category": "associations",
    "files": {
      "default": "/logos/american-academy-of-facial-esthetics-aafe--default.svg",
      "black": "/logos/american-academy-of-facial-esthetics-aafe--black.svg",
      "white": "/logos/american-academy-of-facial-esthetics-aafe--white.svg"
    }
  },
  {
    "name": "American Academy of Pediatric Dentistry AAPD",
    "slug": "american-academy-of-pediatric-dentistry-aapd",
    "node": "8843:84",
    "category": "associations",
    "files": {
      "default": "/logos/american-academy-of-pediatric-dentistry-aapd--default.svg",
      "black": "/logos/american-academy-of-pediatric-dentistry-aapd--black.svg",
      "white": "/logos/american-academy-of-pediatric-dentistry-aapd--white.svg"
    }
  },
  {
    "name": "American Association",
    "slug": "american-association",
    "node": "8834:22",
    "category": "associations",
    "files": {
      "default": "/logos/american-association--default.svg",
      "black": "/logos/american-association--black.svg",
      "white": "/logos/american-association--white.svg"
    }
  },
  {
    "name": "American Board of Endodontics",
    "slug": "american-board-of-endodontics",
    "node": "8834:25",
    "category": "associations",
    "files": {
      "default": "/logos/american-board-of-endodontics--default.svg",
      "black": "/logos/american-board-of-endodontics--black.svg",
      "white": "/logos/american-board-of-endodontics--white.svg"
    }
  },
  {
    "name": "American Board of general Dentistry",
    "slug": "american-board-of-general-dentistry",
    "node": "8834:24",
    "category": "associations",
    "files": {
      "default": "/logos/american-board-of-general-dentistry--default.svg",
      "black": "/logos/american-board-of-general-dentistry--black.svg",
      "white": "/logos/american-board-of-general-dentistry--white.svg"
    }
  },
  {
    "name": "American board of oral & Maxill of facial surgery",
    "slug": "american-board-of-oral-maxill-of-facial-surgery",
    "node": "8871:10849",
    "category": "associations",
    "files": {
      "default": "/logos/american-board-of-oral-maxill-of-facial-surgery--default.svg",
      "black": "/logos/american-board-of-oral-maxill-of-facial-surgery--black.svg",
      "white": "/logos/american-board-of-oral-maxill-of-facial-surgery--white.svg"
    }
  },
  {
    "name": "American Board Pediatrics ABP",
    "slug": "american-board-pediatrics-abp",
    "node": "8864:159",
    "category": "associations",
    "files": {
      "default": "/logos/american-board-pediatrics-abp--default.svg",
      "black": "/logos/american-board-pediatrics-abp--black.svg",
      "white": "/logos/american-board-pediatrics-abp--white.svg"
    }
  },
  {
    "name": "AZDA",
    "slug": "azda",
    "node": "8851:4957",
    "category": "associations",
    "files": {
      "default": "/logos/azda--default.svg",
      "black": "/logos/azda--black.svg",
      "white": "/logos/azda--white.svg"
    }
  },
  {
    "name": "Board ELigible",
    "slug": "board-eligible",
    "node": "8843:61",
    "category": "associations",
    "files": {
      "default": "/logos/board-eligible--default.svg",
      "black": "/logos/board-eligible--black.svg",
      "white": "/logos/board-eligible--white.svg"
    }
  },
  {
    "name": "California dental associationCDA",
    "slug": "california-dental-associationcda",
    "node": "8861:824",
    "category": "associations",
    "files": {
      "default": "/logos/california-dental-associationcda--default.svg",
      "black": "/logos/california-dental-associationcda--black.svg",
      "white": "/logos/california-dental-associationcda--white.svg"
    }
  },
  {
    "name": "Canadian Dental Association",
    "slug": "canadian-dental-association",
    "node": "8901:32",
    "category": "associations",
    "files": {
      "default": "/logos/canadian-dental-association--default.svg",
      "black": "/logos/canadian-dental-association--black.svg",
      "white": "/logos/canadian-dental-association--white.svg"
    }
  },
  {
    "name": "CCDS",
    "slug": "ccds",
    "node": "8892:476",
    "category": "associations",
    "files": {
      "default": "/logos/ccds--default.svg",
      "black": "/logos/ccds--black.svg",
      "white": "/logos/ccds--white.svg"
    }
  },
  {
    "name": "Charlotte Dental Society",
    "slug": "charlotte-dental-society",
    "node": "8834:41",
    "category": "associations",
    "files": {
      "default": "/logos/charlotte-dental-society--default.svg",
      "black": "/logos/charlotte-dental-society--black.svg",
      "white": "/logos/charlotte-dental-society--white.svg"
    }
  },
  {
    "name": "chicago-dental-society",
    "slug": "chicago-dental-society",
    "node": "8866:8521",
    "category": "associations",
    "files": {
      "default": "/logos/chicago-dental-society--default.svg",
      "black": "/logos/chicago-dental-society--black.svg",
      "white": "/logos/chicago-dental-society--white.svg"
    }
  },
  {
    "name": "Cincinnati dental society",
    "slug": "cincinnati-dental-society",
    "node": "8866:8878",
    "category": "associations",
    "files": {
      "default": "/logos/cincinnati-dental-society--default.svg",
      "black": "/logos/cincinnati-dental-society--black.svg",
      "white": "/logos/cincinnati-dental-society--white.svg"
    }
  },
  {
    "name": "District of Columbia Dental Society",
    "slug": "district-of-columbia-dental-society",
    "node": "8892:664",
    "category": "associations",
    "files": {
      "default": "/logos/district-of-columbia-dental-society--default.svg",
      "black": "/logos/district-of-columbia-dental-society--black.svg",
      "white": "/logos/district-of-columbia-dental-society--white.svg"
    }
  },
  {
    "name": "FDA",
    "slug": "fda",
    "node": "8871:11011",
    "category": "associations",
    "files": {
      "default": "/logos/fda--default.svg",
      "white": "/logos/fda--white.svg",
      "black": "/logos/fda--black.svg"
    }
  },
  {
    "name": "Florida association of orthodontists",
    "slug": "florida-association-of-orthodontists",
    "node": "8871:11238",
    "category": "associations",
    "files": {
      "default": "/logos/florida-association-of-orthodontists--default.svg",
      "black": "/logos/florida-association-of-orthodontists--black.svg",
      "white": "/logos/florida-association-of-orthodontists--white.svg"
    }
  },
  {
    "name": "GAO - georgia association of orthodontists",
    "slug": "gao-georgia-association-of-orthodontists",
    "node": "8892:611",
    "category": "associations",
    "files": {
      "default": "/logos/gao-georgia-association-of-orthodontists--default.svg",
      "black": "/logos/gao-georgia-association-of-orthodontists--black.svg",
      "white": "/logos/gao-georgia-association-of-orthodontists--white.svg"
    }
  },
  {
    "name": "IKDA",
    "slug": "ikda",
    "node": "8834:36",
    "category": "associations",
    "files": {
      "default": "/logos/ikda--default.svg",
      "black": "/logos/ikda--black.svg",
      "white": "/logos/ikda--white.svg"
    }
  },
  {
    "name": "Illinois state dental society",
    "slug": "illinois-state-dental-society",
    "node": "8864:450",
    "category": "associations",
    "files": {
      "default": "/logos/illinois-state-dental-society--default.svg",
      "black": "/logos/illinois-state-dental-society--black.svg",
      "white": "/logos/illinois-state-dental-society--white.svg"
    }
  },
  {
    "name": "International Association  for",
    "slug": "international-association-for",
    "node": "8873:69",
    "category": "associations",
    "files": {
      "default": "/logos/international-association-for--default.svg",
      "black": "/logos/international-association-for--black.svg",
      "white": "/logos/international-association-for--white.svg"
    }
  },
  {
    "name": "Leon Contry Dental association",
    "slug": "leon-contry-dental-association",
    "node": "8864:93",
    "category": "associations",
    "files": {
      "default": "/logos/leon-contry-dental-association--default.svg",
      "black": "/logos/leon-contry-dental-association--black.svg",
      "white": "/logos/leon-contry-dental-association--white.svg"
    }
  },
  {
    "name": "Louisiana Dental Accociation",
    "slug": "louisiana-dental-accociation",
    "node": "8834:32",
    "category": "associations",
    "files": {
      "default": "/logos/louisiana-dental-accociation--default.svg",
      "black": "/logos/louisiana-dental-accociation--black.svg",
      "white": "/logos/louisiana-dental-accociation--white.svg"
    }
  },
  {
    "name": "Michigan association of orthodontists MAO",
    "slug": "michigan-association-of-orthodontists-mao",
    "node": "8871:11389",
    "category": "associations",
    "files": {
      "default": "/logos/michigan-association-of-orthodontists-mao--default.svg",
      "black": "/logos/michigan-association-of-orthodontists-mao--black.svg",
      "white": "/logos/michigan-association-of-orthodontists-mao--white.svg"
    }
  },
  {
    "name": "michigan dental association MDA",
    "slug": "michigan-dental-association-mda",
    "node": "8845:6620",
    "category": "associations",
    "files": {
      "default": "/logos/michigan-dental-association-mda--default.svg",
      "black": "/logos/michigan-dental-association-mda--black.svg",
      "white": "/logos/michigan-dental-association-mda--white.svg"
    }
  },
  {
    "name": "Middle Atlantic Society",
    "slug": "middle-atlantic-society",
    "node": "8851:5490",
    "category": "associations",
    "files": {
      "default": "/logos/middle-atlantic-society--default.svg",
      "black": "/logos/middle-atlantic-society--black.svg",
      "white": "/logos/middle-atlantic-society--white.svg"
    }
  },
  {
    "name": "morris county dentist",
    "slug": "morris-county-dentist",
    "node": "8900:9",
    "category": "associations",
    "files": {
      "default": "/logos/morris-county-dentist--default.svg",
      "black": "/logos/morris-county-dentist--black.svg",
      "white": "/logos/morris-county-dentist--white.svg"
    }
  },
  {
    "name": "NCCA",
    "slug": "ncca",
    "node": "8871:11408",
    "category": "associations",
    "files": {
      "default": "/logos/ncca--default.svg",
      "black": "/logos/ncca--black.svg",
      "white": "/logos/ncca--white.svg"
    }
  },
  {
    "name": "NCDS- North Carolina Dental Society",
    "slug": "ncds-north-carolina-dental-society",
    "node": "8834:43",
    "category": "associations",
    "files": {
      "default": "/logos/ncds-north-carolina-dental-society--default.svg",
      "black": "/logos/ncds-north-carolina-dental-society--black.svg",
      "white": "/logos/ncds-north-carolina-dental-society--white.svg"
    }
  },
  {
    "name": "NESO",
    "slug": "neso",
    "node": "8834:16",
    "category": "associations",
    "files": {
      "default": "/logos/neso--default.svg",
      "white": "/logos/neso--white.svg",
      "black": "/logos/neso--black.svg"
    }
  },
  {
    "name": "New jersey association of orthodontists njao",
    "slug": "new-jersey-association-of-orthodontists-njao",
    "node": "8851:5009",
    "category": "associations",
    "files": {
      "default": "/logos/new-jersey-association-of-orthodontists-njao--default.svg",
      "black": "/logos/new-jersey-association-of-orthodontists-njao--black.svg",
      "white": "/logos/new-jersey-association-of-orthodontists-njao--white.svg"
    }
  },
  {
    "name": "NJDA",
    "slug": "njda",
    "node": "8834:12",
    "category": "associations",
    "files": {
      "default": "/logos/njda--default.svg",
      "black": "/logos/njda--black.svg",
      "white": "/logos/njda--white.svg"
    }
  },
  {
    "name": "Official orthodontist of the florida state seminoles",
    "slug": "official-orthodontist-of-the-florida-state-seminoles",
    "node": "8866:9053",
    "category": "associations",
    "files": {
      "default": "/logos/official-orthodontist-of-the-florida-state-seminoles--default.svg",
      "black": "/logos/official-orthodontist-of-the-florida-state-seminoles--black.svg",
      "white": "/logos/official-orthodontist-of-the-florida-state-seminoles--white.svg"
    }
  },
  {
    "name": "Ohio Dental Association",
    "slug": "ohio-dental-association",
    "node": "8845:6665",
    "category": "associations",
    "files": {
      "default": "/logos/ohio-dental-association--default.svg",
      "white": "/logos/ohio-dental-association--white.svg",
      "black": "/logos/ohio-dental-association--black.svg"
    }
  },
  {
    "name": "PAO",
    "slug": "pao",
    "node": "8834:26",
    "category": "associations",
    "files": {
      "default": "/logos/pao--default.svg",
      "black": "/logos/pao--black.svg",
      "white": "/logos/pao--white.svg"
    }
  },
  {
    "name": "PDA",
    "slug": "pda",
    "node": "8834:23",
    "category": "associations",
    "files": {
      "default": "/logos/pda--default.svg",
      "black": "/logos/pda--black.svg",
      "white": "/logos/pda--white.svg"
    }
  },
  {
    "name": "RCDC",
    "slug": "rcdc",
    "node": "8892:274",
    "category": "associations",
    "files": {
      "default": "/logos/rcdc--default.svg",
      "black": "/logos/rcdc--black.svg",
      "white": "/logos/rcdc--white.svg"
    }
  },
  {
    "name": "SAO- Southern Association of Orthodontists",
    "slug": "sao-southern-association-of-orthodontists",
    "node": "8834:42",
    "category": "associations",
    "files": {
      "default": "/logos/sao-southern-association-of-orthodontists--default.svg",
      "black": "/logos/sao-southern-association-of-orthodontists--black.svg",
      "white": "/logos/sao-southern-association-of-orthodontists--white.svg"
    }
  },
  {
    "name": "sdds",
    "slug": "sdds",
    "node": "8901:207",
    "category": "associations",
    "files": {
      "default": "/logos/sdds--default.svg",
      "black": "/logos/sdds--black.svg",
      "white": "/logos/sdds--white.svg"
    }
  },
  {
    "name": "South Florida Academy of Orthodontists",
    "slug": "south-florida-academy-of-orthodontists",
    "node": "8834:31",
    "category": "associations",
    "files": {
      "default": "/logos/south-florida-academy-of-orthodontists--default.svg",
      "black": "/logos/south-florida-academy-of-orthodontists--black.svg",
      "white": "/logos/south-florida-academy-of-orthodontists--white.svg"
    }
  },
  {
    "name": "Special Care dentistry Association",
    "slug": "special-care-dentistry-association",
    "node": "8892:502",
    "category": "associations",
    "files": {
      "default": "/logos/special-care-dentistry-association--default.svg",
      "black": "/logos/special-care-dentistry-association--black.svg",
      "white": "/logos/special-care-dentistry-association--white.svg"
    }
  },
  {
    "name": "Texasdental association TDA",
    "slug": "texasdental-association-tda",
    "node": "8871:10839",
    "category": "associations",
    "files": {
      "black": "/logos/texasdental-association-tda--black.svg",
      "default": "/logos/texasdental-association-tda--default.svg",
      "white": "/logos/texasdental-association-tda--white.svg"
    }
  },
  {
    "name": "Tmj-Default",
    "slug": "tmj-default",
    "node": "8851:5012",
    "category": "associations",
    "files": {
      "default": "/logos/tmj-default--default.svg",
      "black": "/logos/tmj-default--black.svg",
      "white": "/logos/tmj-default--white.svg"
    }
  },
  {
    "name": "Utah Dental Association",
    "slug": "utah-dental-association",
    "node": "8892:517",
    "category": "associations",
    "files": {
      "default": "/logos/utah-dental-association--default.svg",
      "black": "/logos/utah-dental-association--black.svg",
      "white": "/logos/utah-dental-association--white.svg"
    }
  },
  {
    "name": "Virginia dental association",
    "slug": "virginia-dental-association",
    "node": "8871:11398",
    "category": "associations",
    "files": {
      "default": "/logos/virginia-dental-association--default.svg",
      "black": "/logos/virginia-dental-association--black.svg",
      "white": "/logos/virginia-dental-association--white.svg"
    }
  },
  {
    "name": "5280 Magazine best Orthodontist",
    "slug": "5280-magazine-best-orthodontist",
    "node": "8834:60",
    "category": "awards",
    "files": {
      "default": "/logos/5280-magazine-best-orthodontist--default.svg",
      "black": "/logos/5280-magazine-best-orthodontist--black.svg",
      "white": "/logos/5280-magazine-best-orthodontist--white.svg"
    }
  },
  {
    "name": "Americas Top Doctor",
    "slug": "americas-top-doctor",
    "node": "8892:580",
    "category": "awards",
    "files": {
      "default": "/logos/americas-top-doctor--default.svg",
      "black": "/logos/americas-top-doctor--variant2.svg",
      "white": "/logos/americas-top-doctor--variant3.svg"
    }
  },
  {
    "name": "Awarded top dentist",
    "slug": "awarded-top-dentist",
    "node": "8866:8491",
    "category": "awards",
    "files": {
      "default": "/logos/awarded-top-dentist--default.svg",
      "black": "/logos/awarded-top-dentist--black.svg",
      "white": "/logos/awarded-top-dentist--white.svg"
    }
  },
  {
    "name": "Best In the pnw",
    "slug": "best-in-the-pnw",
    "node": "8938:3",
    "category": "awards",
    "files": {
      "default": "/logos/best-in-the-pnw--default.svg",
      "black": "/logos/best-in-the-pnw--black.svg",
      "white": "/logos/best-in-the-pnw--white.svg"
    }
  },
  {
    "name": "Best of cobb presented by cobb life magazine 2020",
    "slug": "best-of-cobb-presented-by-cobb-life-magazine-2020",
    "node": "8866:9108",
    "category": "awards",
    "files": {
      "default": "/logos/best-of-cobb-presented-by-cobb-life-magazine-2020--default.svg",
      "black": "/logos/best-of-cobb-presented-by-cobb-life-magazine-2020--black.svg",
      "white": "/logos/best-of-cobb-presented-by-cobb-life-magazine-2020--white.svg"
    }
  },
  {
    "name": "Best of cobb presented by cobb life magazine 2021",
    "slug": "best-of-cobb-presented-by-cobb-life-magazine-2021",
    "node": "8868:9955",
    "category": "awards",
    "files": {
      "default": "/logos/best-of-cobb-presented-by-cobb-life-magazine-2021--default.svg",
      "black": "/logos/best-of-cobb-presented-by-cobb-life-magazine-2021--black.svg",
      "white": "/logos/best-of-cobb-presented-by-cobb-life-magazine-2021--white.svg"
    }
  },
  {
    "name": "best of loudoun",
    "slug": "best-of-loudoun",
    "node": "8898:45",
    "category": "awards",
    "files": {
      "default": "/logos/best-of-loudoun--default.svg",
      "black": "/logos/best-of-loudoun--black.svg",
      "white": "/logos/best-of-loudoun--white.svg"
    }
  },
  {
    "name": "Best of new braunfels 2023",
    "slug": "best-of-new-braunfels-2023",
    "node": "8868:9850",
    "category": "awards",
    "files": {
      "black": "/logos/best-of-new-braunfels-2023--black.svg",
      "white": "/logos/best-of-new-braunfels-2023--white.svg",
      "default": "/logos/best-of-new-braunfels-2023--default.svg"
    }
  },
  {
    "name": "Best of the Brazos Valley",
    "slug": "best-of-the-brazos-valley",
    "node": "8895:25",
    "category": "awards",
    "files": {
      "default": "/logos/best-of-the-brazos-valley--default.svg",
      "black": "/logos/best-of-the-brazos-valley--black.svg",
      "white": "/logos/best-of-the-brazos-valley--white.svg"
    }
  },
  {
    "name": "best Orthodontist Office of Bucks County",
    "slug": "best-orthodontist-office-of-bucks-county",
    "node": "8901:231",
    "category": "awards",
    "files": {
      "default": "/logos/best-orthodontist-office-of-bucks-county--default.svg",
      "black": "/logos/best-orthodontist-office-of-bucks-county--black.svg",
      "white": "/logos/best-orthodontist-office-of-bucks-county--white.svg"
    }
  },
  {
    "name": "Best Southern Triad",
    "slug": "best-southern-triad",
    "node": "8892:648",
    "category": "awards",
    "files": {
      "default": "/logos/best-southern-triad--default.svg",
      "black": "/logos/best-southern-triad--black.svg",
      "white": "/logos/best-southern-triad--white.svg"
    }
  },
  {
    "name": "bestofboston",
    "slug": "bestofboston",
    "node": "8898:72",
    "category": "awards",
    "files": {
      "default": "/logos/bestofboston--default.svg",
      "black": "/logos/bestofboston--black.svg",
      "white": "/logos/bestofboston--white.svg"
    }
  },
  {
    "name": "fatd badge",
    "slug": "fatd-badge",
    "node": "8892:655",
    "category": "awards",
    "files": {
      "default": "/logos/fatd-badge--default.svg",
      "black": "/logos/fatd-badge--black.svg",
      "white": "/logos/fatd-badge--white.svg"
    }
  },
  {
    "name": "Insite+A-List+2024+Peoples+Choice+WEB+ONLY+(1)",
    "slug": "insite-a-list-2024-peoples-choice-web-only-1",
    "node": "8895:8",
    "category": "awards",
    "files": {
      "default": "/logos/insite-a-list-2024-peoples-choice-web-only-1--default.svg",
      "black": "/logos/insite-a-list-2024-peoples-choice-web-only-1--black.svg",
      "white": "/logos/insite-a-list-2024-peoples-choice-web-only-1--white.svg"
    }
  },
  {
    "name": "locals love us Award winner",
    "slug": "locals-love-us-award-winner",
    "node": "8892:412",
    "category": "awards",
    "files": {
      "default": "/logos/locals-love-us-award-winner--default.svg",
      "black": "/logos/locals-love-us-award-winner--black.svg",
      "white": "/logos/locals-love-us-award-winner--white.svg"
    }
  },
  {
    "name": "Minnesota-Monthly-Best-Dentists",
    "slug": "minnesota-monthly-best-dentists",
    "node": "8901:43",
    "category": "awards",
    "files": {
      "default": "/logos/minnesota-monthly-best-dentists--default.svg",
      "white": "/logos/minnesota-monthly-best-dentists--white.svg",
      "black": "/logos/minnesota-monthly-best-dentists--black.svg"
    }
  },
  {
    "name": "Monterey County's Best Orthodontist",
    "slug": "monterey-county-s-best-orthodontist",
    "node": "8866:9030",
    "category": "awards",
    "files": {
      "default": "/logos/monterey-county-s-best-orthodontist--default.svg",
      "black": "/logos/monterey-county-s-best-orthodontist--black.svg",
      "white": "/logos/monterey-county-s-best-orthodontist--white.svg"
    }
  },
  {
    "name": "MPLS-St-Paul-Top-Dentists.png",
    "slug": "mpls-st-paul-top-dentists-png",
    "node": "8871:11364",
    "category": "awards",
    "files": {
      "default": "/logos/mpls-st-paul-top-dentists-png--default.svg",
      "black": "/logos/mpls-st-paul-top-dentists-png--black.svg",
      "white": "/logos/mpls-st-paul-top-dentists-png--white.svg"
    }
  },
  {
    "name": "Nj Top Dentists",
    "slug": "nj-top-dentists",
    "node": "8834:18",
    "category": "awards",
    "files": {
      "default": "/logos/nj-top-dentists--default.svg",
      "white": "/logos/nj-top-dentists--white.svg",
      "black": "/logos/nj-top-dentists--black.svg"
    }
  },
  {
    "name": "phoenix Magazine Top dentists",
    "slug": "phoenix-magazine-top-dentists",
    "node": "8892:554",
    "category": "awards",
    "files": {
      "default": "/logos/phoenix-magazine-top-dentists--default.svg",
      "black": "/logos/phoenix-magazine-top-dentists--black.svg",
      "white": "/logos/phoenix-magazine-top-dentists--white.svg"
    }
  },
  {
    "name": "San Marcos daily record Best of hays 2021",
    "slug": "san-marcos-daily-record-best-of-hays-2021",
    "node": "8868:10599",
    "category": "awards",
    "files": {
      "black": "/logos/san-marcos-daily-record-best-of-hays-2021--black.svg",
      "white": "/logos/san-marcos-daily-record-best-of-hays-2021--white.svg",
      "default": "/logos/san-marcos-daily-record-best-of-hays-2021--default.svg"
    }
  },
  {
    "name": "Tallahassee Magazines best of Tallahassee",
    "slug": "tallahassee-magazines-best-of-tallahassee",
    "node": "8892:565",
    "category": "awards",
    "files": {
      "default": "/logos/tallahassee-magazines-best-of-tallahassee--default.svg",
      "black": "/logos/tallahassee-magazines-best-of-tallahassee--black.svg",
      "white": "/logos/tallahassee-magazines-best-of-tallahassee--white.svg"
    }
  },
  {
    "name": "The Eagle Readers Choice Award",
    "slug": "the-eagle-readers-choice-award",
    "node": "8900:19",
    "category": "awards",
    "files": {
      "default": "/logos/the-eagle-readers-choice-award--default.svg",
      "black": "/logos/the-eagle-readers-choice-award--black.svg",
      "white": "/logos/the-eagle-readers-choice-award--white.svg"
    }
  },
  {
    "name": "The Triads Best",
    "slug": "the-triads-best",
    "node": "8892:641",
    "category": "awards",
    "files": {
      "default": "/logos/the-triads-best--default.svg",
      "black": "/logos/the-triads-best--black.svg",
      "white": "/logos/the-triads-best--white.svg"
    }
  },
  {
    "name": "threebestrated",
    "slug": "threebestrated",
    "node": "8892:541",
    "category": "awards",
    "files": {
      "default": "/logos/threebestrated--default.svg",
      "black": "/logos/threebestrated--black.svg",
      "white": "/logos/threebestrated--white.svg"
    }
  },
  {
    "name": "Top doctor by leading physicials",
    "slug": "top-doctor-by-leading-physicials",
    "node": "8866:8401",
    "category": "awards",
    "files": {
      "default": "/logos/top-doctor-by-leading-physicials--default.svg",
      "black": "/logos/top-doctor-by-leading-physicials--black.svg",
      "white": "/logos/top-doctor-by-leading-physicials--white.svg"
    }
  },
  {
    "name": "Top Rated Orthodontist",
    "slug": "top-rated-orthodontist",
    "node": "8834:57",
    "category": "awards",
    "files": {
      "default": "/logos/top-rated-orthodontist--default.svg",
      "black": "/logos/top-rated-orthodontist--black.svg",
      "white": "/logos/top-rated-orthodontist--white.svg"
    }
  },
  {
    "name": "Top Rated orthodontist office in Colorado",
    "slug": "top-rated-orthodontist-office-in-colorado",
    "node": "8834:59",
    "category": "awards",
    "files": {
      "default": "/logos/top-rated-orthodontist-office-in-colorado--default.svg",
      "black": "/logos/top-rated-orthodontist-office-in-colorado--black.svg",
      "white": "/logos/top-rated-orthodontist-office-in-colorado--white.svg"
    }
  },
  {
    "name": "Voted #1 Orthodontist since 2014",
    "slug": "voted-1-orthodontist-since-2014",
    "node": "8851:6528",
    "category": "awards",
    "files": {
      "default": "/logos/voted-1-orthodontist-since-2014--default.svg",
      "black": "/logos/voted-1-orthodontist-since-2014--black.svg",
      "white": "/logos/voted-1-orthodontist-since-2014--white.svg"
    }
  },
  {
    "name": "Voted Best of cobb 2019",
    "slug": "voted-best-of-cobb-2019",
    "node": "8868:10787",
    "category": "awards",
    "files": {
      "default": "/logos/voted-best-of-cobb-2019--default.svg",
      "black": "/logos/voted-best-of-cobb-2019--black.svg",
      "white": "/logos/voted-best-of-cobb-2019--white.svg"
    }
  },
  {
    "name": "3m clarity aligners",
    "slug": "3m-clarity-aligners",
    "node": "8892:251",
    "category": "products",
    "files": {
      "default": "/logos/3m-clarity-aligners--default.svg",
      "black": "/logos/3m-clarity-aligners--black.svg",
      "white": "/logos/3m-clarity-aligners--white.svg"
    }
  },
  {
    "name": "Angel Aligner",
    "slug": "angel-aligner",
    "node": "8892:634",
    "category": "products",
    "files": {
      "default": "/logos/angel-aligner--default.svg",
      "black": "/logos/angel-aligner--black.svg",
      "white": "/logos/angel-aligner--white.svg"
    }
  },
  {
    "name": "Aoralscan 3",
    "slug": "aoralscan-3",
    "node": "8866:8388",
    "category": "products",
    "files": {
      "default": "/logos/aoralscan-3--default.svg",
      "black": "/logos/aoralscan-3--black.svg",
      "white": "/logos/aoralscan-3--white.svg"
    }
  },
  {
    "name": "Blue Diamond (Top 1%) Invisalign Provider 2024",
    "slug": "blue-diamond-top-1-invisalign-provider-2024",
    "node": "8990:95",
    "category": "products",
    "files": {
      "default": "/logos/blue-diamond-top-1-invisalign-provider-2024--default.svg",
      "black": "/logos/blue-diamond-top-1-invisalign-provider-2024--black.svg",
      "white": "/logos/blue-diamond-top-1-invisalign-provider-2024--white.svg"
    }
  },
  {
    "name": "Blue Diamond Invisalign Provider 2025",
    "slug": "blue-diamond-invisalign-provider-2025",
    "node": "8990:124",
    "category": "products",
    "files": {
      "default": "/logos/blue-diamond-invisalign-provider-2025--default.svg",
      "black": "/logos/blue-diamond-invisalign-provider-2025--black.svg",
      "white": "/logos/blue-diamond-invisalign-provider-2025--white.svg"
    }
  },
  {
    "name": "Blue Diamond Invisalign Provider 2026",
    "slug": "blue-diamond-invisalign-provider-2026",
    "node": "9010:10",
    "category": "products",
    "files": {
      "default": "/logos/blue-diamond-invisalign-provider-2026--default.svg",
      "black": "/logos/blue-diamond-invisalign-provider-2026--black.svg",
      "white": "/logos/blue-diamond-invisalign-provider-2026--white.svg"
    }
  },
  {
    "name": "Botox cosmetic Botulinum Toxin Type A",
    "slug": "botox-cosmetic-botulinum-toxin-type-a",
    "node": "8859:636",
    "category": "products",
    "files": {
      "default": "/logos/botox-cosmetic-botulinum-toxin-type-a--default.svg",
      "black": "/logos/botox-cosmetic-botulinum-toxin-type-a--black.svg",
      "white": "/logos/botox-cosmetic-botulinum-toxin-type-a--white.svg"
    }
  },
  {
    "name": "Brava By Brius",
    "slug": "brava-by-brius",
    "node": "8851:5624",
    "category": "products",
    "files": {
      "default": "/logos/brava-by-brius--default.svg",
      "black": "/logos/brava-by-brius--black.svg",
      "white": "/logos/brava-by-brius--white.svg"
    }
  },
  {
    "name": "CandidPro",
    "slug": "candidpro",
    "node": "8834:45",
    "category": "products",
    "files": {
      "default": "/logos/candidpro--default.svg",
      "black": "/logos/candidpro--black.svg",
      "white": "/logos/candidpro--white.svg"
    }
  },
  {
    "name": "Carestream dental",
    "slug": "carestream-dental",
    "node": "8871:11043",
    "category": "products",
    "files": {
      "default": "/logos/carestream-dental--default.svg",
      "black": "/logos/carestream-dental--black.svg",
      "white": "/logos/carestream-dental--white.svg"
    }
  },
  {
    "name": "Clarity Advaced ceramic brackets",
    "slug": "clarity-advaced-ceramic-brackets",
    "node": "8861:748",
    "category": "products",
    "files": {
      "default": "/logos/clarity-advaced-ceramic-brackets--default.svg",
      "black": "/logos/clarity-advaced-ceramic-brackets--black.svg",
      "white": "/logos/clarity-advaced-ceramic-brackets--white.svg"
    }
  },
  {
    "name": "DamonBraces-Logo 1",
    "slug": "damonbraces-logo-1",
    "node": "8892:265",
    "category": "products",
    "files": {
      "default": "/logos/damonbraces-logo-1--default.svg",
      "black": "/logos/damonbraces-logo-1--black.svg",
      "white": "/logos/damonbraces-logo-1--white.svg"
    }
  },
  {
    "name": "DamonSmile",
    "slug": "damonsmile",
    "node": "8834:48",
    "category": "products",
    "files": {
      "default": "/logos/damonsmile--default.svg",
      "black": "/logos/damonsmile--black.svg",
      "white": "/logos/damonsmile--white.svg"
    }
  },
  {
    "name": "DamonUltima",
    "slug": "damonultima",
    "node": "8898:51",
    "category": "products",
    "files": {
      "default": "/logos/damonultima--default.svg",
      "black": "/logos/damonultima--black.svg",
      "white": "/logos/damonultima--white.svg"
    }
  },
  {
    "name": "DentalMonitoring",
    "slug": "dentalmonitoring",
    "node": "8892:601",
    "category": "products",
    "files": {
      "default": "/logos/dentalmonitoring--default.svg",
      "black": "/logos/dentalmonitoring--black.svg",
      "white": "/logos/dentalmonitoring--white.svg"
    }
  },
  {
    "name": "Diamond Invisalign Provider",
    "slug": "diamond-invisalign-provider",
    "node": "8834:10",
    "category": "products",
    "files": {
      "default": "/logos/diamond-invisalign-provider--default.svg",
      "white": "/logos/diamond-invisalign-provider--white.svg",
      "black": "/logos/diamond-invisalign-provider--black.svg"
    }
  },
  {
    "name": "Diamond Invisalign Provider in the world",
    "slug": "diamond-invisalign-provider-in-the-world",
    "node": "8834:58",
    "category": "products",
    "files": {
      "default": "/logos/diamond-invisalign-provider-in-the-world--default.svg",
      "black": "/logos/diamond-invisalign-provider-in-the-world--black.svg",
      "white": "/logos/diamond-invisalign-provider-in-the-world--white.svg"
    }
  },
  {
    "name": "Diamond Plus Invisalign Provider",
    "slug": "diamond-plus-invisalign-provider",
    "node": "8834:11",
    "category": "products",
    "files": {
      "white": "/logos/diamond-plus-invisalign-provider--white.svg",
      "black": "/logos/diamond-plus-invisalign-provider--black.svg",
      "default": "/logos/diamond-plus-invisalign-provider--default.svg"
    }
  },
  {
    "name": "Dimond+ Invisalign Provider",
    "slug": "dimond-invisalign-provider",
    "node": "8834:19",
    "category": "products",
    "files": {
      "default": "/logos/dimond-invisalign-provider--default.svg",
      "white": "/logos/dimond-invisalign-provider--white.svg",
      "black": "/logos/dimond-invisalign-provider--black.svg"
    }
  },
  {
    "name": "Gold + Invisalign Provider",
    "slug": "gold-invisalign-provider",
    "node": "8834:20",
    "category": "products",
    "files": {
      "default": "/logos/gold-invisalign-provider--default.svg",
      "black": "/logos/gold-invisalign-provider--black.svg",
      "white": "/logos/gold-invisalign-provider--white.svg"
    }
  },
  {
    "name": "inbrace",
    "slug": "inbrace",
    "node": "8834:53",
    "category": "products",
    "files": {
      "default": "/logos/inbrace--default.svg",
      "black": "/logos/inbrace--black.svg",
      "white": "/logos/inbrace--white.svg"
    }
  },
  {
    "name": "Incognito",
    "slug": "incognito",
    "node": "8859:655",
    "category": "products",
    "files": {
      "default": "/logos/incognito--default.svg",
      "black": "/logos/incognito--black.svg",
      "white": "/logos/incognito--white.svg"
    }
  },
  {
    "name": "Invisalign",
    "slug": "invisalign",
    "node": "8834:9",
    "category": "products",
    "files": {
      "default": "/logos/invisalign--default.svg",
      "black": "/logos/invisalign--black.svg",
      "white": "/logos/invisalign--white.svg"
    }
  },
  {
    "name": "Invisalign Teen",
    "slug": "invisalign-teen",
    "node": "8834:21",
    "category": "products",
    "files": {
      "default": "/logos/invisalign-teen--default.svg",
      "black": "/logos/invisalign-teen--black.svg",
      "white": "/logos/invisalign-teen--white.svg"
    }
  },
  {
    "name": "Invisalign Top 1 Provider",
    "slug": "invisalign-top-1-provider",
    "node": "8834:38",
    "category": "products",
    "files": {
      "default": "/logos/invisalign-top-1-provider--default.svg",
      "black": "/logos/invisalign-top-1-provider--black.svg",
      "white": "/logos/invisalign-top-1-provider--white.svg"
    }
  },
  {
    "name": "itero",
    "slug": "itero",
    "node": "8834:39",
    "category": "products",
    "files": {
      "default": "/logos/itero--default.svg",
      "black": "/logos/itero--black.svg",
      "white": "/logos/itero--white.svg"
    }
  },
  {
    "name": "Juvederm oluma xc",
    "slug": "juvederm-oluma-xc",
    "node": "8866:8817",
    "category": "products",
    "files": {
      "default": "/logos/juvederm-oluma-xc--default.svg",
      "black": "/logos/juvederm-oluma-xc--black.svg",
      "white": "/logos/juvederm-oluma-xc--white.svg"
    }
  },
  {
    "name": "Juvederm ultraplus xc",
    "slug": "juvederm-ultraplus-xc",
    "node": "8866:8698",
    "category": "products",
    "files": {
      "default": "/logos/juvederm-ultraplus-xc--default.svg",
      "black": "/logos/juvederm-ultraplus-xc--black.svg",
      "white": "/logos/juvederm-ultraplus-xc--white.svg"
    }
  },
  {
    "name": "kybella deoxycholic acid - Injection 10 mg",
    "slug": "kybella-deoxycholic-acid-injection-10-mg",
    "node": "8866:9044",
    "category": "products",
    "files": {
      "default": "/logos/kybella-deoxycholic-acid-injection-10-mg--default.svg",
      "black": "/logos/kybella-deoxycholic-acid-injection-10-mg--black.svg",
      "white": "/logos/kybella-deoxycholic-acid-injection-10-mg--white.svg"
    }
  },
  {
    "name": "Lectured for Invisalign in the southeast US on early treatment with aligners",
    "slug": "lectured-for-invisalign-in-the-southeast-us-on-early-treatme",
    "node": "8866:8667",
    "category": "products",
    "files": {
      "default": "/logos/lectured-for-invisalign-in-the-southeast-us-on-early-treatme--default.svg",
      "black": "/logos/lectured-for-invisalign-in-the-southeast-us-on-early-treatme--black.svg",
      "white": "/logos/lectured-for-invisalign-in-the-southeast-us-on-early-treatme--white.svg"
    }
  },
  {
    "name": "Light Force",
    "slug": "light-force",
    "node": "8834:52",
    "category": "products",
    "files": {
      "default": "/logos/light-force--default.svg",
      "black": "/logos/light-force--black.svg",
      "white": "/logos/light-force--white.svg"
    }
  },
  {
    "name": "OrthoFX",
    "slug": "orthofx",
    "node": "8834:47",
    "category": "products",
    "files": {
      "default": "/logos/orthofx--default.svg",
      "black": "/logos/orthofx--black.svg",
      "white": "/logos/orthofx--white.svg"
    }
  },
  {
    "name": "Pitts21",
    "slug": "pitts21",
    "node": "8834:35",
    "category": "products",
    "files": {
      "default": "/logos/pitts21--default.svg",
      "black": "/logos/pitts21--black.svg",
      "white": "/logos/pitts21--white.svg"
    }
  },
  {
    "name": "Platinum + Invisalign Provider",
    "slug": "platinum-invisalign-provider-2",
    "node": "8834:61",
    "category": "products",
    "files": {
      "default": "/logos/platinum-invisalign-provider-2--default.svg",
      "black": "/logos/platinum-invisalign-provider-2--black.svg",
      "white": "/logos/platinum-invisalign-provider-2--white.svg"
    }
  },
  {
    "name": "Platinum + Invisalign Provider",
    "slug": "platinum-invisalign-provider-3",
    "node": "8834:62",
    "category": "products",
    "files": {
      "black": "/logos/platinum-invisalign-provider-3--black.svg",
      "white": "/logos/platinum-invisalign-provider-3--white.svg",
      "default": "/logos/platinum-invisalign-provider-3--default.svg"
    }
  },
  {
    "name": "Platinum Invisalign Provider",
    "slug": "platinum-invisalign-provider",
    "node": "8834:17",
    "category": "products",
    "files": {
      "default": "/logos/platinum-invisalign-provider--default.svg",
      "black": "/logos/platinum-invisalign-provider--black.svg",
      "white": "/logos/platinum-invisalign-provider--white.svg"
    }
  },
  {
    "name": "Spark",
    "slug": "spark",
    "node": "8834:34",
    "category": "products",
    "files": {
      "default": "/logos/spark--default.svg",
      "black": "/logos/spark--black.svg",
      "white": "/logos/spark--white.svg"
    }
  },
  {
    "name": "Suresmile",
    "slug": "suresmile",
    "node": "8871:11081",
    "category": "products",
    "files": {
      "default": "/logos/suresmile--default.svg",
      "black": "/logos/suresmile--black.svg",
      "white": "/logos/suresmile--white.svg"
    }
  },
  {
    "name": "TruDenta",
    "slug": "trudenta",
    "node": "8901:257",
    "category": "products",
    "files": {
      "default": "/logos/trudenta--default.svg",
      "black": "/logos/trudenta--black.svg",
      "white": "/logos/trudenta--white.svg"
    }
  },
  {
    "name": "ulab System",
    "slug": "ulab-system",
    "node": "8834:56",
    "category": "products",
    "files": {
      "default": "/logos/ulab-system--default.svg",
      "black": "/logos/ulab-system--black.svg",
      "white": "/logos/ulab-system--white.svg"
    }
  },
  {
    "name": "Yomi",
    "slug": "yomi",
    "node": "8834:46",
    "category": "products",
    "files": {
      "default": "/logos/yomi--default.svg",
      "black": "/logos/yomi--black.svg",
      "white": "/logos/yomi--white.svg"
    }
  },
  {
    "name": "Zoom",
    "slug": "zoom",
    "node": "8845:6549",
    "category": "products",
    "files": {
      "default": "/logos/zoom--default.svg",
      "black": "/logos/zoom--black.svg",
      "white": "/logos/zoom--white.svg"
    }
  },
  {
    "name": "ASU",
    "slug": "asu",
    "node": "8845:5420",
    "category": "education",
    "files": {
      "default": "/logos/asu--default.svg",
      "white": "/logos/asu--white.svg",
      "black": "/logos/asu--black.svg"
    }
  },
  {
    "name": "Brigham Young University BYU",
    "slug": "brigham-young-university-byu",
    "node": "8846:1122",
    "category": "education",
    "files": {
      "default": "/logos/brigham-young-university-byu--default.svg",
      "black": "/logos/brigham-young-university-byu--black.svg",
      "white": "/logos/brigham-young-university-byu--white.svg"
    }
  },
  {
    "name": "College of diplomates",
    "slug": "college-of-diplomates",
    "node": "8834:14",
    "category": "education",
    "files": {
      "default": "/logos/college-of-diplomates--default.svg",
      "black": "/logos/college-of-diplomates--black.svg",
      "white": "/logos/college-of-diplomates--white.svg"
    }
  },
  {
    "name": "Harvard University",
    "slug": "harvard-university",
    "node": "8845:6503",
    "category": "education",
    "files": {
      "default": "/logos/harvard-university--default.svg",
      "black": "/logos/harvard-university--black.svg",
      "white": "/logos/harvard-university--white.svg"
    }
  },
  {
    "name": "kappa lambda chapter",
    "slug": "kappa-lambda-chapter",
    "node": "8871:10818",
    "category": "education",
    "files": {
      "default": "/logos/kappa-lambda-chapter--default.svg",
      "white": "/logos/kappa-lambda-chapter--white.svg",
      "black": "/logos/kappa-lambda-chapter--black.svg"
    }
  },
  {
    "name": "northwestern",
    "slug": "northwestern",
    "node": "8845:6572",
    "category": "education",
    "files": {
      "default": "/logos/northwestern--default.svg",
      "black": "/logos/northwestern--black.svg",
      "white": "/logos/northwestern--white.svg"
    }
  },
  {
    "name": "OKU",
    "slug": "oku",
    "node": "8898:61",
    "category": "education",
    "files": {
      "default": "/logos/oku--default.svg",
      "black": "/logos/oku--black.svg",
      "white": "/logos/oku--white.svg"
    }
  },
  {
    "name": "Oregon health science university ohsu",
    "slug": "oregon-health-science-university-ohsu",
    "node": "8851:4963",
    "category": "education",
    "files": {
      "default": "/logos/oregon-health-science-university-ohsu--default.svg",
      "black": "/logos/oregon-health-science-university-ohsu--black.svg",
      "white": "/logos/oregon-health-science-university-ohsu--white.svg"
    }
  },
  {
    "name": "Ortho faculty at UMKC School of Dentistry",
    "slug": "ortho-faculty-at-umkc-school-of-dentistry",
    "node": "8834:40",
    "category": "education",
    "files": {
      "default": "/logos/ortho-faculty-at-umkc-school-of-dentistry--default.svg",
      "black": "/logos/ortho-faculty-at-umkc-school-of-dentistry--black.svg",
      "white": "/logos/ortho-faculty-at-umkc-school-of-dentistry--white.svg"
    }
  },
  {
    "name": "Seattle study club hamburg",
    "slug": "seattle-study-club-hamburg",
    "node": "8866:8500",
    "category": "education",
    "files": {
      "default": "/logos/seattle-study-club-hamburg--default.svg",
      "black": "/logos/seattle-study-club-hamburg--black.svg",
      "white": "/logos/seattle-study-club-hamburg--white.svg"
    }
  },
  {
    "name": "University of Californil",
    "slug": "university-of-californil",
    "node": "8846:1125",
    "category": "education",
    "files": {
      "black": "/logos/university-of-californil--black.svg",
      "white": "/logos/university-of-californil--white.svg",
      "default": "/logos/university-of-californil--default.svg"
    }
  },
  {
    "name": "University of Washington seal 1",
    "slug": "university-of-washington-seal-1",
    "node": "8846:1123",
    "category": "education",
    "files": {
      "white": "/logos/university-of-washington-seal-1--white.svg",
      "default": "/logos/university-of-washington-seal-1--default.svg",
      "black": "/logos/university-of-washington-seal-1--black.svg"
    }
  },
  {
    "name": "Ameritas",
    "slug": "ameritas",
    "node": "8834:28",
    "category": "insurance",
    "files": {
      "default": "/logos/ameritas--default.svg",
      "black": "/logos/ameritas--black.svg",
      "white": "/logos/ameritas--white.svg"
    }
  },
  {
    "name": "Humana-Black",
    "slug": "humana-black",
    "node": "8834:27",
    "category": "insurance",
    "files": {
      "default": "/logos/humana-black--default.svg",
      "black": "/logos/humana-black--black.svg",
      "white": "/logos/humana-black--white.svg"
    }
  },
  {
    "name": "MetLife",
    "slug": "metlife",
    "node": "8834:29",
    "category": "insurance",
    "files": {
      "default": "/logos/metlife--default.svg",
      "black": "/logos/metlife--black.svg",
      "white": "/logos/metlife--white.svg"
    }
  },
  {
    "name": "UMR",
    "slug": "umr",
    "node": "8834:30",
    "category": "insurance",
    "files": {
      "default": "/logos/umr--default.svg",
      "black": "/logos/umr--black.svg",
      "white": "/logos/umr--white.svg"
    }
  },
  {
    "name": "Alda",
    "slug": "alda",
    "node": "8845:6538",
    "category": "community",
    "files": {
      "default": "/logos/alda--default.svg",
      "black": "/logos/alda--black.svg",
      "white": "/logos/alda--white.svg"
    }
  },
  {
    "name": "ALDA",
    "slug": "alda-2",
    "node": "8851:5921",
    "category": "community",
    "files": {
      "default": "/logos/alda-2--default.svg",
      "black": "/logos/alda-2--black.svg",
      "white": "/logos/alda-2--white.svg"
    }
  },
  {
    "name": "alexandergroup",
    "slug": "alexandergroup",
    "node": "8891:197",
    "category": "community",
    "files": {
      "default": "/logos/alexandergroup--default.svg",
      "black": "/logos/alexandergroup--black.svg",
      "white": "/logos/alexandergroup--white.svg"
    }
  },
  {
    "name": "Angle-Northwest-Logo 1",
    "slug": "angle-northwest-logo-1",
    "node": "8873:61",
    "category": "community",
    "files": {
      "default": "/logos/angle-northwest-logo-1--default.svg",
      "black": "/logos/angle-northwest-logo-1--black.svg",
      "white": "/logos/angle-northwest-logo-1--white.svg"
    }
  },
  {
    "name": "Arizona Ortho Study Group",
    "slug": "arizona-ortho-study-group",
    "node": "8870:48",
    "category": "community",
    "files": {
      "default": "/logos/arizona-ortho-study-group--default.svg",
      "black": "/logos/arizona-ortho-study-group--black.svg",
      "white": "/logos/arizona-ortho-study-group--white.svg"
    }
  },
  {
    "name": "Atlanta Parent's",
    "slug": "atlanta-parent-s",
    "node": "8851:5010",
    "category": "community",
    "files": {
      "default": "/logos/atlanta-parent-s--default.svg",
      "black": "/logos/atlanta-parent-s--black.svg",
      "white": "/logos/atlanta-parent-s--white.svg"
    }
  },
  {
    "name": "BRACES Mane In America",
    "slug": "braces-mane-in-america",
    "node": "8834:13",
    "category": "community",
    "files": {
      "default": "/logos/braces-mane-in-america--default.svg",
      "white": "/logos/braces-mane-in-america--white.svg",
      "black": "/logos/braces-mane-in-america--black.svg"
    }
  },
  {
    "name": "Brand Logo",
    "slug": "brand-logo",
    "node": "8845:8290",
    "category": "community",
    "files": {
      "default": "/logos/brand-logo--default.svg",
      "black": "/logos/brand-logo--black.svg",
      "white": "/logos/brand-logo--white.svg"
    }
  },
  {
    "name": "Brand Logo",
    "slug": "brand-logo-2",
    "node": "8845:8297",
    "category": "community",
    "files": {
      "default": "/logos/brand-logo-2--default.svg",
      "black": "/logos/brand-logo-2--black.svg",
      "white": "/logos/brand-logo-2--white.svg"
    }
  },
  {
    "name": "Bullard Family Foundation",
    "slug": "bullard-family-foundation",
    "node": "8892:625",
    "category": "community",
    "files": {
      "default": "/logos/bullard-family-foundation--default.svg",
      "black": "/logos/bullard-family-foundation--black.svg",
      "white": "/logos/bullard-family-foundation--white.svg"
    }
  },
  {
    "name": "CAO",
    "slug": "cao",
    "node": "8841:129",
    "category": "community",
    "files": {
      "default": "/logos/cao--default.svg",
      "white": "/logos/cao--white.svg",
      "black": "/logos/cao--black.svg"
    }
  },
  {
    "name": "CMDA",
    "slug": "cmda",
    "node": "8841:190",
    "category": "community",
    "files": {
      "default": "/logos/cmda--default.svg",
      "black": "/logos/cmda--black.svg",
      "white": "/logos/cmda--white.svg"
    }
  },
  {
    "name": "EHASO",
    "slug": "ehaso",
    "node": "8834:44",
    "category": "community",
    "files": {
      "default": "/logos/ehaso--default.svg",
      "black": "/logos/ehaso--black.svg",
      "white": "/logos/ehaso--white.svg"
    }
  },
  {
    "name": "Ferguson libary",
    "slug": "ferguson-libary",
    "node": "8859:281",
    "category": "community",
    "files": {
      "default": "/logos/ferguson-libary--default.svg",
      "black": "/logos/ferguson-libary--black.svg",
      "white": "/logos/ferguson-libary--white.svg"
    }
  },
  {
    "name": "Gallatins",
    "slug": "gallatins",
    "node": "8851:5021",
    "category": "community",
    "files": {
      "default": "/logos/gallatins--default.svg",
      "black": "/logos/gallatins--black.svg",
      "white": "/logos/gallatins--white.svg"
    }
  },
  {
    "name": "Huntington",
    "slug": "huntington",
    "node": "8834:49",
    "category": "community",
    "files": {
      "default": "/logos/huntington--default.svg",
      "black": "/logos/huntington--black.svg",
      "white": "/logos/huntington--white.svg"
    }
  },
  {
    "name": "IDA-Indiana-gray 1",
    "slug": "ida-indiana-gray-1",
    "node": "8892:213",
    "category": "community",
    "files": {
      "default": "/logos/ida-indiana-gray-1--default.svg",
      "black": "/logos/ida-indiana-gray-1--black.svg",
      "white": "/logos/ida-indiana-gray-1--variant3.svg"
    }
  },
  {
    "name": "Leixir",
    "slug": "leixir",
    "node": "8834:50",
    "category": "community",
    "files": {
      "default": "/logos/leixir--default.svg",
      "black": "/logos/leixir--black.svg",
      "white": "/logos/leixir--white.svg"
    }
  },
  {
    "name": "loudoun fav press",
    "slug": "loudoun-fav-press",
    "node": "8898:37",
    "category": "community",
    "files": {
      "default": "/logos/loudoun-fav-press--default.svg",
      "black": "/logos/loudoun-fav-press--black.svg",
      "white": "/logos/loudoun-fav-press--white.svg"
    }
  },
  {
    "name": "mds-foundation",
    "slug": "mds-foundation",
    "node": "8892:243",
    "category": "community",
    "files": {
      "default": "/logos/mds-foundation--default.svg",
      "black": "/logos/mds-foundation--black.svg",
      "white": "/logos/mds-foundation--variant3.svg"
    }
  },
  {
    "name": "NCATD-removebg-preview 2",
    "slug": "ncatd-removebg-preview-2",
    "node": "8892:491",
    "category": "community",
    "files": {
      "default": "/logos/ncatd-removebg-preview-2--default.svg",
      "white": "/logos/ncatd-removebg-preview-2--white.svg",
      "black": "/logos/ncatd-removebg-preview-2--black.svg"
    }
  },
  {
    "name": "NEWJERSEYFAMILY",
    "slug": "newjerseyfamily",
    "node": "8845:6792",
    "category": "community",
    "files": {
      "default": "/logos/newjerseyfamily--default.svg",
      "black": "/logos/newjerseyfamily--black.svg",
      "white": "/logos/newjerseyfamily--white.svg"
    }
  },
  {
    "name": "NewsChannel 8",
    "slug": "newschannel-8",
    "node": "8841:258",
    "category": "community",
    "files": {
      "default": "/logos/newschannel-8--default.svg",
      "black": "/logos/newschannel-8--black.svg",
      "white": "/logos/newschannel-8--white.svg"
    }
  },
  {
    "name": "nextdor",
    "slug": "nextdor",
    "node": "8834:54",
    "category": "community",
    "files": {
      "white": "/logos/nextdor--white.svg",
      "black": "/logos/nextdor--black.svg",
      "default": "/logos/nextdor--default.svg"
    }
  },
  {
    "name": "One hundred black men, Inc.",
    "slug": "one-hundred-black-men-inc",
    "node": "8851:6311",
    "category": "community",
    "files": {
      "default": "/logos/one-hundred-black-men-inc--default.svg",
      "black": "/logos/one-hundred-black-men-inc--black.svg",
      "white": "/logos/one-hundred-black-men-inc--white.svg"
    }
  },
  {
    "name": "Orange",
    "slug": "orange",
    "node": "8841:423",
    "category": "community",
    "files": {
      "default": "/logos/orange--default.svg",
      "black": "/logos/orange--black.svg",
      "white": "/logos/orange--white.svg"
    }
  },
  {
    "name": "Pcso",
    "slug": "pcso",
    "node": "8834:51",
    "category": "community",
    "files": {
      "default": "/logos/pcso--default.svg",
      "black": "/logos/pcso--black.svg",
      "white": "/logos/pcso--white.svg"
    }
  },
  {
    "name": "Promise",
    "slug": "promise",
    "node": "8834:55",
    "category": "community",
    "files": {
      "default": "/logos/promise--default.svg",
      "black": "/logos/promise--black.svg",
      "white": "/logos/promise--white.svg"
    }
  },
  {
    "name": "PTA ever child. one voice",
    "slug": "pta-ever-child-one-voice",
    "node": "8866:8837",
    "category": "community",
    "files": {
      "default": "/logos/pta-ever-child-one-voice--default.svg",
      "black": "/logos/pta-ever-child-one-voice--black.svg",
      "white": "/logos/pta-ever-child-one-voice--white.svg"
    }
  },
  {
    "name": "SB",
    "slug": "sb",
    "node": "8870:35",
    "category": "community",
    "files": {
      "default": "/logos/sb--default.svg",
      "black": "/logos/sb--black.svg",
      "white": "/logos/sb--white.svg"
    }
  },
  {
    "name": "shehancenterlogo-300px 2",
    "slug": "shehancenterlogo-300px-2",
    "node": "8895:15",
    "category": "community",
    "files": {
      "default": "/logos/shehancenterlogo-300px-2--default.svg",
      "black": "/logos/shehancenterlogo-300px-2--black.svg",
      "white": "/logos/shehancenterlogo-300px-2--white.svg"
    }
  },
  {
    "name": "Smiles change lives",
    "slug": "smiles-change-lives",
    "node": "8834:33",
    "category": "community",
    "files": {
      "black": "/logos/smiles-change-lives--black.svg",
      "white": "/logos/smiles-change-lives--white.svg",
      "default": "/logos/smiles-change-lives--default.svg"
    }
  },
  {
    "name": "SOUTHERN ALAMEDA COUNTY",
    "slug": "southern-alameda-county",
    "node": "8845:6959",
    "category": "community",
    "files": {
      "default": "/logos/southern-alameda-county--default.svg",
      "black": "/logos/southern-alameda-county--black.svg",
      "white": "/logos/southern-alameda-county--white.svg"
    }
  },
  {
    "name": "Sports car club of america",
    "slug": "sports-car-club-of-america",
    "node": "8871:11371",
    "category": "community",
    "files": {
      "default": "/logos/sports-car-club-of-america--default.svg",
      "black": "/logos/sports-car-club-of-america--black.svg",
      "white": "/logos/sports-car-club-of-america--white.svg"
    }
  },
  {
    "name": "SSPD test",
    "slug": "sspd-test",
    "node": "8851:5725",
    "category": "community",
    "files": {
      "default": "/logos/sspd-test--default.svg",
      "black": "/logos/sspd-test--black.svg",
      "white": "/logos/sspd-test--white.svg"
    }
  },
  {
    "name": "Tampa bay parenting",
    "slug": "tampa-bay-parenting",
    "node": "8842:12",
    "category": "community",
    "files": {
      "default": "/logos/tampa-bay-parenting--default.svg",
      "white": "/logos/tampa-bay-parenting--white.svg",
      "black": "/logos/tampa-bay-parenting--black.svg"
    }
  },
  {
    "name": "Tampa Bay Rowdies",
    "slug": "tampa-bay-rowdies",
    "node": "8841:342",
    "category": "community",
    "files": {
      "default": "/logos/tampa-bay-rowdies--default.svg",
      "black": "/logos/tampa-bay-rowdies--black.svg",
      "white": "/logos/tampa-bay-rowdies--white.svg"
    }
  },
  {
    "name": "Thaddeus Bullard",
    "slug": "thaddeus-bullard",
    "node": "8841:349",
    "category": "community",
    "files": {
      "default": "/logos/thaddeus-bullard--default.svg",
      "black": "/logos/thaddeus-bullard--black.svg",
      "white": "/logos/thaddeus-bullard--white.svg"
    }
  },
  {
    "name": "Tiouch events",
    "slug": "tiouch-events",
    "node": "8841:564",
    "category": "community",
    "files": {
      "default": "/logos/tiouch-events--default.svg",
      "black": "/logos/tiouch-events--black.svg",
      "white": "/logos/tiouch-events--white.svg"
    }
  },
  {
    "name": "Triad Moms on Main",
    "slug": "triad-moms-on-main",
    "node": "8898:79",
    "category": "community",
    "files": {
      "default": "/logos/triad-moms-on-main--default.svg",
      "black": "/logos/triad-moms-on-main--black.svg",
      "white": "/logos/triad-moms-on-main--white.svg"
    }
  },
  {
    "name": "Voices for children",
    "slug": "voices-for-children",
    "node": "8842:5",
    "category": "community",
    "files": {
      "default": "/logos/voices-for-children--default.svg",
      "black": "/logos/voices-for-children--black.svg",
      "white": "/logos/voices-for-children--white.svg"
    }
  },
  {
    "name": "women owned",
    "slug": "women-owned",
    "node": "8845:6870",
    "category": "community",
    "files": {
      "default": "/logos/women-owned--default.svg",
      "black": "/logos/women-owned--black.svg",
      "white": "/logos/women-owned--white.svg"
    }
  }
];

export const totalLogos = logos.length;

export const logoCatCounts = logos.reduce(
  (acc, l) => ((acc[l.category] = (acc[l.category] ?? 0) + 1), acc),
  {} as Record<LogoCategory, number>
);
